// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Documento.proto

package com.gcalsolaro.grpc.artifact.model;

/**
 * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Documento}
 */
public  final class Documento extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gcalsolaro.grpc.artifact.model.Documento)
    DocumentoOrBuilder {
  // Use Documento.newBuilder() to construct.
  private Documento(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Documento() {
    idDocumento_ = 0;
    descrizione_ = "";
    nomeFile_ = "";
    pathFile_ = "";
    pathTmp_ = "";
    useridCancRec_ = "";
    useridIns_ = "";
    useridMod_ = "";
    stato_ = "";
    checksum_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Documento(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            idDocumento_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            descrizione_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraCancRec_ != null) {
              subBuilder = dtOraCancRec_.toBuilder();
            }
            dtOraCancRec_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraCancRec_);
              dtOraCancRec_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraIns_ != null) {
              subBuilder = dtOraIns_.toBuilder();
            }
            dtOraIns_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraIns_);
              dtOraIns_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraMod_ != null) {
              subBuilder = dtOraMod_.toBuilder();
            }
            dtOraMod_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraMod_);
              dtOraMod_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            nomeFile_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            pathFile_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            pathTmp_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            useridCancRec_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            useridIns_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            useridMod_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            stato_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            checksum_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gcalsolaro.grpc.artifact.model.DocumentoOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gcalsolaro.grpc.artifact.model.DocumentoOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Documento_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gcalsolaro.grpc.artifact.model.Documento.class, com.gcalsolaro.grpc.artifact.model.Documento.Builder.class);
  }

  public static final int IDDOCUMENTO_FIELD_NUMBER = 1;
  private int idDocumento_;
  /**
   * <code>int32 idDocumento = 1;</code>
   */
  public int getIdDocumento() {
    return idDocumento_;
  }

  public static final int DESCRIZIONE_FIELD_NUMBER = 2;
  private volatile java.lang.Object descrizione_;
  /**
   * <code>string descrizione = 2;</code>
   */
  public java.lang.String getDescrizione() {
    java.lang.Object ref = descrizione_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descrizione_ = s;
      return s;
    }
  }
  /**
   * <code>string descrizione = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescrizioneBytes() {
    java.lang.Object ref = descrizione_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descrizione_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DTORACANCREC_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp dtOraCancRec_;
  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  public boolean hasDtOraCancRec() {
    return dtOraCancRec_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  public com.google.protobuf.Timestamp getDtOraCancRec() {
    return dtOraCancRec_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraCancRec_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraCancRecOrBuilder() {
    return getDtOraCancRec();
  }

  public static final int DTORAINS_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp dtOraIns_;
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  public boolean hasDtOraIns() {
    return dtOraIns_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  public com.google.protobuf.Timestamp getDtOraIns() {
    return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
    return getDtOraIns();
  }

  public static final int DTORAMOD_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp dtOraMod_;
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  public boolean hasDtOraMod() {
    return dtOraMod_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  public com.google.protobuf.Timestamp getDtOraMod() {
    return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
    return getDtOraMod();
  }

  public static final int NOMEFILE_FIELD_NUMBER = 6;
  private volatile java.lang.Object nomeFile_;
  /**
   * <code>string nomeFile = 6;</code>
   */
  public java.lang.String getNomeFile() {
    java.lang.Object ref = nomeFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeFile_ = s;
      return s;
    }
  }
  /**
   * <code>string nomeFile = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNomeFileBytes() {
    java.lang.Object ref = nomeFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATHFILE_FIELD_NUMBER = 7;
  private volatile java.lang.Object pathFile_;
  /**
   * <code>string pathFile = 7;</code>
   */
  public java.lang.String getPathFile() {
    java.lang.Object ref = pathFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pathFile_ = s;
      return s;
    }
  }
  /**
   * <code>string pathFile = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPathFileBytes() {
    java.lang.Object ref = pathFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pathFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATHTMP_FIELD_NUMBER = 8;
  private volatile java.lang.Object pathTmp_;
  /**
   * <code>string pathTmp = 8;</code>
   */
  public java.lang.String getPathTmp() {
    java.lang.Object ref = pathTmp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pathTmp_ = s;
      return s;
    }
  }
  /**
   * <code>string pathTmp = 8;</code>
   */
  public com.google.protobuf.ByteString
      getPathTmpBytes() {
    java.lang.Object ref = pathTmp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pathTmp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDCANCREC_FIELD_NUMBER = 9;
  private volatile java.lang.Object useridCancRec_;
  /**
   * <code>string useridCancRec = 9;</code>
   */
  public java.lang.String getUseridCancRec() {
    java.lang.Object ref = useridCancRec_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridCancRec_ = s;
      return s;
    }
  }
  /**
   * <code>string useridCancRec = 9;</code>
   */
  public com.google.protobuf.ByteString
      getUseridCancRecBytes() {
    java.lang.Object ref = useridCancRec_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridCancRec_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDINS_FIELD_NUMBER = 10;
  private volatile java.lang.Object useridIns_;
  /**
   * <code>string useridIns = 10;</code>
   */
  public java.lang.String getUseridIns() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridIns_ = s;
      return s;
    }
  }
  /**
   * <code>string useridIns = 10;</code>
   */
  public com.google.protobuf.ByteString
      getUseridInsBytes() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridIns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDMOD_FIELD_NUMBER = 11;
  private volatile java.lang.Object useridMod_;
  /**
   * <code>string useridMod = 11;</code>
   */
  public java.lang.String getUseridMod() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridMod_ = s;
      return s;
    }
  }
  /**
   * <code>string useridMod = 11;</code>
   */
  public com.google.protobuf.ByteString
      getUseridModBytes() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridMod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATO_FIELD_NUMBER = 12;
  private volatile java.lang.Object stato_;
  /**
   * <code>string stato = 12;</code>
   */
  public java.lang.String getStato() {
    java.lang.Object ref = stato_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stato_ = s;
      return s;
    }
  }
  /**
   * <code>string stato = 12;</code>
   */
  public com.google.protobuf.ByteString
      getStatoBytes() {
    java.lang.Object ref = stato_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stato_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKSUM_FIELD_NUMBER = 13;
  private volatile java.lang.Object checksum_;
  /**
   * <code>string checksum = 13;</code>
   */
  public java.lang.String getChecksum() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checksum_ = s;
      return s;
    }
  }
  /**
   * <code>string checksum = 13;</code>
   */
  public com.google.protobuf.ByteString
      getChecksumBytes() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idDocumento_ != 0) {
      output.writeInt32(1, idDocumento_);
    }
    if (!getDescrizioneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, descrizione_);
    }
    if (dtOraCancRec_ != null) {
      output.writeMessage(3, getDtOraCancRec());
    }
    if (dtOraIns_ != null) {
      output.writeMessage(4, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      output.writeMessage(5, getDtOraMod());
    }
    if (!getNomeFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nomeFile_);
    }
    if (!getPathFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pathFile_);
    }
    if (!getPathTmpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pathTmp_);
    }
    if (!getUseridCancRecBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, useridCancRec_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, useridMod_);
    }
    if (!getStatoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, stato_);
    }
    if (!getChecksumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, checksum_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idDocumento_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idDocumento_);
    }
    if (!getDescrizioneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, descrizione_);
    }
    if (dtOraCancRec_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDtOraCancRec());
    }
    if (dtOraIns_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDtOraMod());
    }
    if (!getNomeFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nomeFile_);
    }
    if (!getPathFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pathFile_);
    }
    if (!getPathTmpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pathTmp_);
    }
    if (!getUseridCancRecBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, useridCancRec_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, useridMod_);
    }
    if (!getStatoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, stato_);
    }
    if (!getChecksumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, checksum_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gcalsolaro.grpc.artifact.model.Documento)) {
      return super.equals(obj);
    }
    com.gcalsolaro.grpc.artifact.model.Documento other = (com.gcalsolaro.grpc.artifact.model.Documento) obj;

    boolean result = true;
    result = result && (getIdDocumento()
        == other.getIdDocumento());
    result = result && getDescrizione()
        .equals(other.getDescrizione());
    result = result && (hasDtOraCancRec() == other.hasDtOraCancRec());
    if (hasDtOraCancRec()) {
      result = result && getDtOraCancRec()
          .equals(other.getDtOraCancRec());
    }
    result = result && (hasDtOraIns() == other.hasDtOraIns());
    if (hasDtOraIns()) {
      result = result && getDtOraIns()
          .equals(other.getDtOraIns());
    }
    result = result && (hasDtOraMod() == other.hasDtOraMod());
    if (hasDtOraMod()) {
      result = result && getDtOraMod()
          .equals(other.getDtOraMod());
    }
    result = result && getNomeFile()
        .equals(other.getNomeFile());
    result = result && getPathFile()
        .equals(other.getPathFile());
    result = result && getPathTmp()
        .equals(other.getPathTmp());
    result = result && getUseridCancRec()
        .equals(other.getUseridCancRec());
    result = result && getUseridIns()
        .equals(other.getUseridIns());
    result = result && getUseridMod()
        .equals(other.getUseridMod());
    result = result && getStato()
        .equals(other.getStato());
    result = result && getChecksum()
        .equals(other.getChecksum());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDDOCUMENTO_FIELD_NUMBER;
    hash = (53 * hash) + getIdDocumento();
    hash = (37 * hash) + DESCRIZIONE_FIELD_NUMBER;
    hash = (53 * hash) + getDescrizione().hashCode();
    if (hasDtOraCancRec()) {
      hash = (37 * hash) + DTORACANCREC_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraCancRec().hashCode();
    }
    if (hasDtOraIns()) {
      hash = (37 * hash) + DTORAINS_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraIns().hashCode();
    }
    if (hasDtOraMod()) {
      hash = (37 * hash) + DTORAMOD_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraMod().hashCode();
    }
    hash = (37 * hash) + NOMEFILE_FIELD_NUMBER;
    hash = (53 * hash) + getNomeFile().hashCode();
    hash = (37 * hash) + PATHFILE_FIELD_NUMBER;
    hash = (53 * hash) + getPathFile().hashCode();
    hash = (37 * hash) + PATHTMP_FIELD_NUMBER;
    hash = (53 * hash) + getPathTmp().hashCode();
    hash = (37 * hash) + USERIDCANCREC_FIELD_NUMBER;
    hash = (53 * hash) + getUseridCancRec().hashCode();
    hash = (37 * hash) + USERIDINS_FIELD_NUMBER;
    hash = (53 * hash) + getUseridIns().hashCode();
    hash = (37 * hash) + USERIDMOD_FIELD_NUMBER;
    hash = (53 * hash) + getUseridMod().hashCode();
    hash = (37 * hash) + STATO_FIELD_NUMBER;
    hash = (53 * hash) + getStato().hashCode();
    hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
    hash = (53 * hash) + getChecksum().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Documento parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gcalsolaro.grpc.artifact.model.Documento prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Documento}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gcalsolaro.grpc.artifact.model.Documento)
      com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gcalsolaro.grpc.artifact.model.DocumentoOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gcalsolaro.grpc.artifact.model.DocumentoOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Documento_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gcalsolaro.grpc.artifact.model.Documento.class, com.gcalsolaro.grpc.artifact.model.Documento.Builder.class);
    }

    // Construct using com.gcalsolaro.grpc.artifact.model.Documento.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      idDocumento_ = 0;

      descrizione_ = "";

      if (dtOraCancRecBuilder_ == null) {
        dtOraCancRec_ = null;
      } else {
        dtOraCancRec_ = null;
        dtOraCancRecBuilder_ = null;
      }
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }
      nomeFile_ = "";

      pathFile_ = "";

      pathTmp_ = "";

      useridCancRec_ = "";

      useridIns_ = "";

      useridMod_ = "";

      stato_ = "";

      checksum_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gcalsolaro.grpc.artifact.model.DocumentoOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor;
    }

    public com.gcalsolaro.grpc.artifact.model.Documento getDefaultInstanceForType() {
      return com.gcalsolaro.grpc.artifact.model.Documento.getDefaultInstance();
    }

    public com.gcalsolaro.grpc.artifact.model.Documento build() {
      com.gcalsolaro.grpc.artifact.model.Documento result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gcalsolaro.grpc.artifact.model.Documento buildPartial() {
      com.gcalsolaro.grpc.artifact.model.Documento result = new com.gcalsolaro.grpc.artifact.model.Documento(this);
      result.idDocumento_ = idDocumento_;
      result.descrizione_ = descrizione_;
      if (dtOraCancRecBuilder_ == null) {
        result.dtOraCancRec_ = dtOraCancRec_;
      } else {
        result.dtOraCancRec_ = dtOraCancRecBuilder_.build();
      }
      if (dtOraInsBuilder_ == null) {
        result.dtOraIns_ = dtOraIns_;
      } else {
        result.dtOraIns_ = dtOraInsBuilder_.build();
      }
      if (dtOraModBuilder_ == null) {
        result.dtOraMod_ = dtOraMod_;
      } else {
        result.dtOraMod_ = dtOraModBuilder_.build();
      }
      result.nomeFile_ = nomeFile_;
      result.pathFile_ = pathFile_;
      result.pathTmp_ = pathTmp_;
      result.useridCancRec_ = useridCancRec_;
      result.useridIns_ = useridIns_;
      result.useridMod_ = useridMod_;
      result.stato_ = stato_;
      result.checksum_ = checksum_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gcalsolaro.grpc.artifact.model.Documento) {
        return mergeFrom((com.gcalsolaro.grpc.artifact.model.Documento)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gcalsolaro.grpc.artifact.model.Documento other) {
      if (other == com.gcalsolaro.grpc.artifact.model.Documento.getDefaultInstance()) return this;
      if (other.getIdDocumento() != 0) {
        setIdDocumento(other.getIdDocumento());
      }
      if (!other.getDescrizione().isEmpty()) {
        descrizione_ = other.descrizione_;
        onChanged();
      }
      if (other.hasDtOraCancRec()) {
        mergeDtOraCancRec(other.getDtOraCancRec());
      }
      if (other.hasDtOraIns()) {
        mergeDtOraIns(other.getDtOraIns());
      }
      if (other.hasDtOraMod()) {
        mergeDtOraMod(other.getDtOraMod());
      }
      if (!other.getNomeFile().isEmpty()) {
        nomeFile_ = other.nomeFile_;
        onChanged();
      }
      if (!other.getPathFile().isEmpty()) {
        pathFile_ = other.pathFile_;
        onChanged();
      }
      if (!other.getPathTmp().isEmpty()) {
        pathTmp_ = other.pathTmp_;
        onChanged();
      }
      if (!other.getUseridCancRec().isEmpty()) {
        useridCancRec_ = other.useridCancRec_;
        onChanged();
      }
      if (!other.getUseridIns().isEmpty()) {
        useridIns_ = other.useridIns_;
        onChanged();
      }
      if (!other.getUseridMod().isEmpty()) {
        useridMod_ = other.useridMod_;
        onChanged();
      }
      if (!other.getStato().isEmpty()) {
        stato_ = other.stato_;
        onChanged();
      }
      if (!other.getChecksum().isEmpty()) {
        checksum_ = other.checksum_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gcalsolaro.grpc.artifact.model.Documento parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gcalsolaro.grpc.artifact.model.Documento) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int idDocumento_ ;
    /**
     * <code>int32 idDocumento = 1;</code>
     */
    public int getIdDocumento() {
      return idDocumento_;
    }
    /**
     * <code>int32 idDocumento = 1;</code>
     */
    public Builder setIdDocumento(int value) {
      
      idDocumento_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idDocumento = 1;</code>
     */
    public Builder clearIdDocumento() {
      
      idDocumento_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object descrizione_ = "";
    /**
     * <code>string descrizione = 2;</code>
     */
    public java.lang.String getDescrizione() {
      java.lang.Object ref = descrizione_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descrizione_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string descrizione = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescrizioneBytes() {
      java.lang.Object ref = descrizione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descrizione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string descrizione = 2;</code>
     */
    public Builder setDescrizione(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      descrizione_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string descrizione = 2;</code>
     */
    public Builder clearDescrizione() {
      
      descrizione_ = getDefaultInstance().getDescrizione();
      onChanged();
      return this;
    }
    /**
     * <code>string descrizione = 2;</code>
     */
    public Builder setDescrizioneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      descrizione_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dtOraCancRec_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraCancRecBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public boolean hasDtOraCancRec() {
      return dtOraCancRecBuilder_ != null || dtOraCancRec_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public com.google.protobuf.Timestamp getDtOraCancRec() {
      if (dtOraCancRecBuilder_ == null) {
        return dtOraCancRec_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraCancRec_;
      } else {
        return dtOraCancRecBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public Builder setDtOraCancRec(com.google.protobuf.Timestamp value) {
      if (dtOraCancRecBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraCancRec_ = value;
        onChanged();
      } else {
        dtOraCancRecBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public Builder setDtOraCancRec(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraCancRecBuilder_ == null) {
        dtOraCancRec_ = builderForValue.build();
        onChanged();
      } else {
        dtOraCancRecBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public Builder mergeDtOraCancRec(com.google.protobuf.Timestamp value) {
      if (dtOraCancRecBuilder_ == null) {
        if (dtOraCancRec_ != null) {
          dtOraCancRec_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraCancRec_).mergeFrom(value).buildPartial();
        } else {
          dtOraCancRec_ = value;
        }
        onChanged();
      } else {
        dtOraCancRecBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public Builder clearDtOraCancRec() {
      if (dtOraCancRecBuilder_ == null) {
        dtOraCancRec_ = null;
        onChanged();
      } else {
        dtOraCancRec_ = null;
        dtOraCancRecBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraCancRecBuilder() {
      
      onChanged();
      return getDtOraCancRecFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraCancRecOrBuilder() {
      if (dtOraCancRecBuilder_ != null) {
        return dtOraCancRecBuilder_.getMessageOrBuilder();
      } else {
        return dtOraCancRec_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraCancRec_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraCancRecFieldBuilder() {
      if (dtOraCancRecBuilder_ == null) {
        dtOraCancRecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraCancRec(),
                getParentForChildren(),
                isClean());
        dtOraCancRec_ = null;
      }
      return dtOraCancRecBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraIns_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraInsBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public boolean hasDtOraIns() {
      return dtOraInsBuilder_ != null || dtOraIns_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public com.google.protobuf.Timestamp getDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      } else {
        return dtOraInsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public Builder setDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraIns_ = value;
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public Builder setDtOraIns(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = builderForValue.build();
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public Builder mergeDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (dtOraIns_ != null) {
          dtOraIns_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraIns_).mergeFrom(value).buildPartial();
        } else {
          dtOraIns_ = value;
        }
        onChanged();
      } else {
        dtOraInsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public Builder clearDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
        onChanged();
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraInsBuilder() {
      
      onChanged();
      return getDtOraInsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
      if (dtOraInsBuilder_ != null) {
        return dtOraInsBuilder_.getMessageOrBuilder();
      } else {
        return dtOraIns_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraInsFieldBuilder() {
      if (dtOraInsBuilder_ == null) {
        dtOraInsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraIns(),
                getParentForChildren(),
                isClean());
        dtOraIns_ = null;
      }
      return dtOraInsBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraMod_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraModBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public boolean hasDtOraMod() {
      return dtOraModBuilder_ != null || dtOraMod_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public com.google.protobuf.Timestamp getDtOraMod() {
      if (dtOraModBuilder_ == null) {
        return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      } else {
        return dtOraModBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public Builder setDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraMod_ = value;
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public Builder setDtOraMod(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = builderForValue.build();
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public Builder mergeDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (dtOraMod_ != null) {
          dtOraMod_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraMod_).mergeFrom(value).buildPartial();
        } else {
          dtOraMod_ = value;
        }
        onChanged();
      } else {
        dtOraModBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public Builder clearDtOraMod() {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
        onChanged();
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraModBuilder() {
      
      onChanged();
      return getDtOraModFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
      if (dtOraModBuilder_ != null) {
        return dtOraModBuilder_.getMessageOrBuilder();
      } else {
        return dtOraMod_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraModFieldBuilder() {
      if (dtOraModBuilder_ == null) {
        dtOraModBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraMod(),
                getParentForChildren(),
                isClean());
        dtOraMod_ = null;
      }
      return dtOraModBuilder_;
    }

    private java.lang.Object nomeFile_ = "";
    /**
     * <code>string nomeFile = 6;</code>
     */
    public java.lang.String getNomeFile() {
      java.lang.Object ref = nomeFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nomeFile = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNomeFileBytes() {
      java.lang.Object ref = nomeFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nomeFile = 6;</code>
     */
    public Builder setNomeFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nomeFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nomeFile = 6;</code>
     */
    public Builder clearNomeFile() {
      
      nomeFile_ = getDefaultInstance().getNomeFile();
      onChanged();
      return this;
    }
    /**
     * <code>string nomeFile = 6;</code>
     */
    public Builder setNomeFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nomeFile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pathFile_ = "";
    /**
     * <code>string pathFile = 7;</code>
     */
    public java.lang.String getPathFile() {
      java.lang.Object ref = pathFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pathFile = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPathFileBytes() {
      java.lang.Object ref = pathFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pathFile = 7;</code>
     */
    public Builder setPathFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pathFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pathFile = 7;</code>
     */
    public Builder clearPathFile() {
      
      pathFile_ = getDefaultInstance().getPathFile();
      onChanged();
      return this;
    }
    /**
     * <code>string pathFile = 7;</code>
     */
    public Builder setPathFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pathFile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pathTmp_ = "";
    /**
     * <code>string pathTmp = 8;</code>
     */
    public java.lang.String getPathTmp() {
      java.lang.Object ref = pathTmp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathTmp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pathTmp = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPathTmpBytes() {
      java.lang.Object ref = pathTmp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathTmp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pathTmp = 8;</code>
     */
    public Builder setPathTmp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pathTmp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pathTmp = 8;</code>
     */
    public Builder clearPathTmp() {
      
      pathTmp_ = getDefaultInstance().getPathTmp();
      onChanged();
      return this;
    }
    /**
     * <code>string pathTmp = 8;</code>
     */
    public Builder setPathTmpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pathTmp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridCancRec_ = "";
    /**
     * <code>string useridCancRec = 9;</code>
     */
    public java.lang.String getUseridCancRec() {
      java.lang.Object ref = useridCancRec_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridCancRec_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridCancRec = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUseridCancRecBytes() {
      java.lang.Object ref = useridCancRec_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridCancRec_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridCancRec = 9;</code>
     */
    public Builder setUseridCancRec(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridCancRec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridCancRec = 9;</code>
     */
    public Builder clearUseridCancRec() {
      
      useridCancRec_ = getDefaultInstance().getUseridCancRec();
      onChanged();
      return this;
    }
    /**
     * <code>string useridCancRec = 9;</code>
     */
    public Builder setUseridCancRecBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridCancRec_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridIns_ = "";
    /**
     * <code>string useridIns = 10;</code>
     */
    public java.lang.String getUseridIns() {
      java.lang.Object ref = useridIns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridIns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridIns = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUseridInsBytes() {
      java.lang.Object ref = useridIns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridIns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridIns = 10;</code>
     */
    public Builder setUseridIns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridIns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 10;</code>
     */
    public Builder clearUseridIns() {
      
      useridIns_ = getDefaultInstance().getUseridIns();
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 10;</code>
     */
    public Builder setUseridInsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridIns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridMod_ = "";
    /**
     * <code>string useridMod = 11;</code>
     */
    public java.lang.String getUseridMod() {
      java.lang.Object ref = useridMod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridMod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridMod = 11;</code>
     */
    public com.google.protobuf.ByteString
        getUseridModBytes() {
      java.lang.Object ref = useridMod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridMod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridMod = 11;</code>
     */
    public Builder setUseridMod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridMod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 11;</code>
     */
    public Builder clearUseridMod() {
      
      useridMod_ = getDefaultInstance().getUseridMod();
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 11;</code>
     */
    public Builder setUseridModBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridMod_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stato_ = "";
    /**
     * <code>string stato = 12;</code>
     */
    public java.lang.String getStato() {
      java.lang.Object ref = stato_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stato_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stato = 12;</code>
     */
    public com.google.protobuf.ByteString
        getStatoBytes() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stato_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stato = 12;</code>
     */
    public Builder setStato(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stato_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stato = 12;</code>
     */
    public Builder clearStato() {
      
      stato_ = getDefaultInstance().getStato();
      onChanged();
      return this;
    }
    /**
     * <code>string stato = 12;</code>
     */
    public Builder setStatoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stato_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object checksum_ = "";
    /**
     * <code>string checksum = 13;</code>
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checksum = 13;</code>
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checksum = 13;</code>
     */
    public Builder setChecksum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checksum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 13;</code>
     */
    public Builder clearChecksum() {
      
      checksum_ = getDefaultInstance().getChecksum();
      onChanged();
      return this;
    }
    /**
     * <code>string checksum = 13;</code>
     */
    public Builder setChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checksum_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gcalsolaro.grpc.artifact.model.Documento)
  }

  // @@protoc_insertion_point(class_scope:com.gcalsolaro.grpc.artifact.model.Documento)
  private static final com.gcalsolaro.grpc.artifact.model.Documento DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gcalsolaro.grpc.artifact.model.Documento();
  }

  public static com.gcalsolaro.grpc.artifact.model.Documento getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Documento>
      PARSER = new com.google.protobuf.AbstractParser<Documento>() {
    public Documento parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Documento(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Documento> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Documento> getParserForType() {
    return PARSER;
  }

  public com.gcalsolaro.grpc.artifact.model.Documento getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

