// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Documento.proto

package com.gcalsolaro.grpc.artifact.model;

public interface DocumentoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.model.Documento)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idDocumento = 1;</code>
   */
  int getIdDocumento();

  /**
   * <code>string descrizione = 2;</code>
   */
  java.lang.String getDescrizione();
  /**
   * <code>string descrizione = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescrizioneBytes();

  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  boolean hasDtOraCancRec();
  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  com.google.protobuf.Timestamp getDtOraCancRec();
  /**
   * <code>.google.protobuf.Timestamp dtOraCancRec = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraCancRecOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  boolean hasDtOraIns();
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  com.google.protobuf.Timestamp getDtOraIns();
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  boolean hasDtOraMod();
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  com.google.protobuf.Timestamp getDtOraMod();
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder();

  /**
   * <code>string nomeFile = 6;</code>
   */
  java.lang.String getNomeFile();
  /**
   * <code>string nomeFile = 6;</code>
   */
  com.google.protobuf.ByteString
      getNomeFileBytes();

  /**
   * <code>string pathFile = 7;</code>
   */
  java.lang.String getPathFile();
  /**
   * <code>string pathFile = 7;</code>
   */
  com.google.protobuf.ByteString
      getPathFileBytes();

  /**
   * <code>string pathTmp = 8;</code>
   */
  java.lang.String getPathTmp();
  /**
   * <code>string pathTmp = 8;</code>
   */
  com.google.protobuf.ByteString
      getPathTmpBytes();

  /**
   * <code>string useridCancRec = 9;</code>
   */
  java.lang.String getUseridCancRec();
  /**
   * <code>string useridCancRec = 9;</code>
   */
  com.google.protobuf.ByteString
      getUseridCancRecBytes();

  /**
   * <code>string useridIns = 10;</code>
   */
  java.lang.String getUseridIns();
  /**
   * <code>string useridIns = 10;</code>
   */
  com.google.protobuf.ByteString
      getUseridInsBytes();

  /**
   * <code>string useridMod = 11;</code>
   */
  java.lang.String getUseridMod();
  /**
   * <code>string useridMod = 11;</code>
   */
  com.google.protobuf.ByteString
      getUseridModBytes();

  /**
   * <code>string stato = 12;</code>
   */
  java.lang.String getStato();
  /**
   * <code>string stato = 12;</code>
   */
  com.google.protobuf.ByteString
      getStatoBytes();

  /**
   * <code>string checksum = 13;</code>
   */
  java.lang.String getChecksum();
  /**
   * <code>string checksum = 13;</code>
   */
  com.google.protobuf.ByteString
      getChecksumBytes();
}
