// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Istanza.proto

package com.gcalsolaro.grpc.artifact.model;

/**
 * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Istanza}
 */
public  final class Istanza extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gcalsolaro.grpc.artifact.model.Istanza)
    IstanzaOrBuilder {
  // Use Istanza.newBuilder() to construct.
  private Istanza(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Istanza() {
    idIstanza_ = 0;
    archiviazione_ = "";
    cFiscale_ = "";
    cIstanza_ = "";
    denominazione_ = "";
    info_ = "";
    jsonPratica_ = "";
    oggetto_ = "";
    proIstanza_ = 0;
    useridIns_ = "";
    useridMod_ = "";
    documenti_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Istanza(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            idIstanza_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            archiviazione_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cFiscale_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cIstanza_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            denominazione_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtDomanda_ != null) {
              subBuilder = dtDomanda_.toBuilder();
            }
            dtDomanda_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtDomanda_);
              dtDomanda_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraAcquisizione_ != null) {
              subBuilder = dtOraAcquisizione_.toBuilder();
            }
            dtOraAcquisizione_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraAcquisizione_);
              dtOraAcquisizione_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraIns_ != null) {
              subBuilder = dtOraIns_.toBuilder();
            }
            dtOraIns_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraIns_);
              dtOraIns_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraMod_ != null) {
              subBuilder = dtOraMod_.toBuilder();
            }
            dtOraMod_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraMod_);
              dtOraMod_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            info_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            jsonPratica_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            oggetto_ = s;
            break;
          }
          case 104: {

            proIstanza_ = input.readInt32();
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            useridIns_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            useridMod_ = s;
            break;
          }
          case 130: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraAnnullamento_ != null) {
              subBuilder = dtOraAnnullamento_.toBuilder();
            }
            dtOraAnnullamento_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraAnnullamento_);
              dtOraAnnullamento_ = subBuilder.buildPartial();
            }

            break;
          }
          case 138: {
            com.gcalsolaro.grpc.artifact.model.Utente.Builder subBuilder = null;
            if (utente_ != null) {
              subBuilder = utente_.toBuilder();
            }
            utente_ = input.readMessage(com.gcalsolaro.grpc.artifact.model.Utente.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(utente_);
              utente_ = subBuilder.buildPartial();
            }

            break;
          }
          case 146: {
            if (!((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
              documenti_ = new java.util.ArrayList<com.gcalsolaro.grpc.artifact.model.Documento>();
              mutable_bitField0_ |= 0x00020000;
            }
            documenti_.add(
                input.readMessage(com.gcalsolaro.grpc.artifact.model.Documento.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00020000) == 0x00020000)) {
        documenti_ = java.util.Collections.unmodifiableList(documenti_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gcalsolaro.grpc.artifact.model.IstanzaOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Istanza_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gcalsolaro.grpc.artifact.model.IstanzaOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Istanza_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gcalsolaro.grpc.artifact.model.Istanza.class, com.gcalsolaro.grpc.artifact.model.Istanza.Builder.class);
  }

  private int bitField0_;
  public static final int IDISTANZA_FIELD_NUMBER = 1;
  private int idIstanza_;
  /**
   * <code>int32 idIstanza = 1;</code>
   */
  public int getIdIstanza() {
    return idIstanza_;
  }

  public static final int ARCHIVIAZIONE_FIELD_NUMBER = 2;
  private volatile java.lang.Object archiviazione_;
  /**
   * <code>string archiviazione = 2;</code>
   */
  public java.lang.String getArchiviazione() {
    java.lang.Object ref = archiviazione_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      archiviazione_ = s;
      return s;
    }
  }
  /**
   * <code>string archiviazione = 2;</code>
   */
  public com.google.protobuf.ByteString
      getArchiviazioneBytes() {
    java.lang.Object ref = archiviazione_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      archiviazione_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CFISCALE_FIELD_NUMBER = 3;
  private volatile java.lang.Object cFiscale_;
  /**
   * <code>string cFiscale = 3;</code>
   */
  public java.lang.String getCFiscale() {
    java.lang.Object ref = cFiscale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cFiscale_ = s;
      return s;
    }
  }
  /**
   * <code>string cFiscale = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCFiscaleBytes() {
    java.lang.Object ref = cFiscale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cFiscale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CISTANZA_FIELD_NUMBER = 4;
  private volatile java.lang.Object cIstanza_;
  /**
   * <code>string cIstanza = 4;</code>
   */
  public java.lang.String getCIstanza() {
    java.lang.Object ref = cIstanza_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cIstanza_ = s;
      return s;
    }
  }
  /**
   * <code>string cIstanza = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCIstanzaBytes() {
    java.lang.Object ref = cIstanza_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cIstanza_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DENOMINAZIONE_FIELD_NUMBER = 5;
  private volatile java.lang.Object denominazione_;
  /**
   * <code>string denominazione = 5;</code>
   */
  public java.lang.String getDenominazione() {
    java.lang.Object ref = denominazione_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      denominazione_ = s;
      return s;
    }
  }
  /**
   * <code>string denominazione = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDenominazioneBytes() {
    java.lang.Object ref = denominazione_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      denominazione_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DTDOMANDA_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp dtDomanda_;
  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  public boolean hasDtDomanda() {
    return dtDomanda_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  public com.google.protobuf.Timestamp getDtDomanda() {
    return dtDomanda_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtDomanda_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtDomandaOrBuilder() {
    return getDtDomanda();
  }

  public static final int DTORAACQUISIZIONE_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp dtOraAcquisizione_;
  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  public boolean hasDtOraAcquisizione() {
    return dtOraAcquisizione_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  public com.google.protobuf.Timestamp getDtOraAcquisizione() {
    return dtOraAcquisizione_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAcquisizione_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraAcquisizioneOrBuilder() {
    return getDtOraAcquisizione();
  }

  public static final int DTORAINS_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp dtOraIns_;
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  public boolean hasDtOraIns() {
    return dtOraIns_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  public com.google.protobuf.Timestamp getDtOraIns() {
    return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
    return getDtOraIns();
  }

  public static final int DTORAMOD_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp dtOraMod_;
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  public boolean hasDtOraMod() {
    return dtOraMod_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  public com.google.protobuf.Timestamp getDtOraMod() {
    return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
    return getDtOraMod();
  }

  public static final int INFO_FIELD_NUMBER = 10;
  private volatile java.lang.Object info_;
  /**
   * <code>string info = 10;</code>
   */
  public java.lang.String getInfo() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      info_ = s;
      return s;
    }
  }
  /**
   * <code>string info = 10;</code>
   */
  public com.google.protobuf.ByteString
      getInfoBytes() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      info_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONPRATICA_FIELD_NUMBER = 11;
  private volatile java.lang.Object jsonPratica_;
  /**
   * <code>string jsonPratica = 11;</code>
   */
  public java.lang.String getJsonPratica() {
    java.lang.Object ref = jsonPratica_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonPratica_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonPratica = 11;</code>
   */
  public com.google.protobuf.ByteString
      getJsonPraticaBytes() {
    java.lang.Object ref = jsonPratica_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonPratica_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OGGETTO_FIELD_NUMBER = 12;
  private volatile java.lang.Object oggetto_;
  /**
   * <code>string oggetto = 12;</code>
   */
  public java.lang.String getOggetto() {
    java.lang.Object ref = oggetto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oggetto_ = s;
      return s;
    }
  }
  /**
   * <code>string oggetto = 12;</code>
   */
  public com.google.protobuf.ByteString
      getOggettoBytes() {
    java.lang.Object ref = oggetto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oggetto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROISTANZA_FIELD_NUMBER = 13;
  private int proIstanza_;
  /**
   * <code>int32 proIstanza = 13;</code>
   */
  public int getProIstanza() {
    return proIstanza_;
  }

  public static final int USERIDINS_FIELD_NUMBER = 14;
  private volatile java.lang.Object useridIns_;
  /**
   * <code>string useridIns = 14;</code>
   */
  public java.lang.String getUseridIns() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridIns_ = s;
      return s;
    }
  }
  /**
   * <code>string useridIns = 14;</code>
   */
  public com.google.protobuf.ByteString
      getUseridInsBytes() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridIns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDMOD_FIELD_NUMBER = 15;
  private volatile java.lang.Object useridMod_;
  /**
   * <code>string useridMod = 15;</code>
   */
  public java.lang.String getUseridMod() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridMod_ = s;
      return s;
    }
  }
  /**
   * <code>string useridMod = 15;</code>
   */
  public com.google.protobuf.ByteString
      getUseridModBytes() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridMod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DTORAANNULLAMENTO_FIELD_NUMBER = 16;
  private com.google.protobuf.Timestamp dtOraAnnullamento_;
  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  public boolean hasDtOraAnnullamento() {
    return dtOraAnnullamento_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  public com.google.protobuf.Timestamp getDtOraAnnullamento() {
    return dtOraAnnullamento_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAnnullamento_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraAnnullamentoOrBuilder() {
    return getDtOraAnnullamento();
  }

  public static final int UTENTE_FIELD_NUMBER = 17;
  private com.gcalsolaro.grpc.artifact.model.Utente utente_;
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  public boolean hasUtente() {
    return utente_ != null;
  }
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.Utente getUtente() {
    return utente_ == null ? com.gcalsolaro.grpc.artifact.model.Utente.getDefaultInstance() : utente_;
  }
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder getUtenteOrBuilder() {
    return getUtente();
  }

  public static final int DOCUMENTI_FIELD_NUMBER = 18;
  private java.util.List<com.gcalsolaro.grpc.artifact.model.Documento> documenti_;
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  public java.util.List<com.gcalsolaro.grpc.artifact.model.Documento> getDocumentiList() {
    return documenti_;
  }
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  public java.util.List<? extends com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder> 
      getDocumentiOrBuilderList() {
    return documenti_;
  }
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  public int getDocumentiCount() {
    return documenti_.size();
  }
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.Documento getDocumenti(int index) {
    return documenti_.get(index);
  }
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder getDocumentiOrBuilder(
      int index) {
    return documenti_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idIstanza_ != 0) {
      output.writeInt32(1, idIstanza_);
    }
    if (!getArchiviazioneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, archiviazione_);
    }
    if (!getCFiscaleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cFiscale_);
    }
    if (!getCIstanzaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cIstanza_);
    }
    if (!getDenominazioneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, denominazione_);
    }
    if (dtDomanda_ != null) {
      output.writeMessage(6, getDtDomanda());
    }
    if (dtOraAcquisizione_ != null) {
      output.writeMessage(7, getDtOraAcquisizione());
    }
    if (dtOraIns_ != null) {
      output.writeMessage(8, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      output.writeMessage(9, getDtOraMod());
    }
    if (!getInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, info_);
    }
    if (!getJsonPraticaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, jsonPratica_);
    }
    if (!getOggettoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, oggetto_);
    }
    if (proIstanza_ != 0) {
      output.writeInt32(13, proIstanza_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, useridMod_);
    }
    if (dtOraAnnullamento_ != null) {
      output.writeMessage(16, getDtOraAnnullamento());
    }
    if (utente_ != null) {
      output.writeMessage(17, getUtente());
    }
    for (int i = 0; i < documenti_.size(); i++) {
      output.writeMessage(18, documenti_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idIstanza_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idIstanza_);
    }
    if (!getArchiviazioneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, archiviazione_);
    }
    if (!getCFiscaleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cFiscale_);
    }
    if (!getCIstanzaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cIstanza_);
    }
    if (!getDenominazioneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, denominazione_);
    }
    if (dtDomanda_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDtDomanda());
    }
    if (dtOraAcquisizione_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDtOraAcquisizione());
    }
    if (dtOraIns_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDtOraMod());
    }
    if (!getInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, info_);
    }
    if (!getJsonPraticaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, jsonPratica_);
    }
    if (!getOggettoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, oggetto_);
    }
    if (proIstanza_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, proIstanza_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, useridMod_);
    }
    if (dtOraAnnullamento_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getDtOraAnnullamento());
    }
    if (utente_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getUtente());
    }
    for (int i = 0; i < documenti_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, documenti_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gcalsolaro.grpc.artifact.model.Istanza)) {
      return super.equals(obj);
    }
    com.gcalsolaro.grpc.artifact.model.Istanza other = (com.gcalsolaro.grpc.artifact.model.Istanza) obj;

    boolean result = true;
    result = result && (getIdIstanza()
        == other.getIdIstanza());
    result = result && getArchiviazione()
        .equals(other.getArchiviazione());
    result = result && getCFiscale()
        .equals(other.getCFiscale());
    result = result && getCIstanza()
        .equals(other.getCIstanza());
    result = result && getDenominazione()
        .equals(other.getDenominazione());
    result = result && (hasDtDomanda() == other.hasDtDomanda());
    if (hasDtDomanda()) {
      result = result && getDtDomanda()
          .equals(other.getDtDomanda());
    }
    result = result && (hasDtOraAcquisizione() == other.hasDtOraAcquisizione());
    if (hasDtOraAcquisizione()) {
      result = result && getDtOraAcquisizione()
          .equals(other.getDtOraAcquisizione());
    }
    result = result && (hasDtOraIns() == other.hasDtOraIns());
    if (hasDtOraIns()) {
      result = result && getDtOraIns()
          .equals(other.getDtOraIns());
    }
    result = result && (hasDtOraMod() == other.hasDtOraMod());
    if (hasDtOraMod()) {
      result = result && getDtOraMod()
          .equals(other.getDtOraMod());
    }
    result = result && getInfo()
        .equals(other.getInfo());
    result = result && getJsonPratica()
        .equals(other.getJsonPratica());
    result = result && getOggetto()
        .equals(other.getOggetto());
    result = result && (getProIstanza()
        == other.getProIstanza());
    result = result && getUseridIns()
        .equals(other.getUseridIns());
    result = result && getUseridMod()
        .equals(other.getUseridMod());
    result = result && (hasDtOraAnnullamento() == other.hasDtOraAnnullamento());
    if (hasDtOraAnnullamento()) {
      result = result && getDtOraAnnullamento()
          .equals(other.getDtOraAnnullamento());
    }
    result = result && (hasUtente() == other.hasUtente());
    if (hasUtente()) {
      result = result && getUtente()
          .equals(other.getUtente());
    }
    result = result && getDocumentiList()
        .equals(other.getDocumentiList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDISTANZA_FIELD_NUMBER;
    hash = (53 * hash) + getIdIstanza();
    hash = (37 * hash) + ARCHIVIAZIONE_FIELD_NUMBER;
    hash = (53 * hash) + getArchiviazione().hashCode();
    hash = (37 * hash) + CFISCALE_FIELD_NUMBER;
    hash = (53 * hash) + getCFiscale().hashCode();
    hash = (37 * hash) + CISTANZA_FIELD_NUMBER;
    hash = (53 * hash) + getCIstanza().hashCode();
    hash = (37 * hash) + DENOMINAZIONE_FIELD_NUMBER;
    hash = (53 * hash) + getDenominazione().hashCode();
    if (hasDtDomanda()) {
      hash = (37 * hash) + DTDOMANDA_FIELD_NUMBER;
      hash = (53 * hash) + getDtDomanda().hashCode();
    }
    if (hasDtOraAcquisizione()) {
      hash = (37 * hash) + DTORAACQUISIZIONE_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraAcquisizione().hashCode();
    }
    if (hasDtOraIns()) {
      hash = (37 * hash) + DTORAINS_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraIns().hashCode();
    }
    if (hasDtOraMod()) {
      hash = (37 * hash) + DTORAMOD_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraMod().hashCode();
    }
    hash = (37 * hash) + INFO_FIELD_NUMBER;
    hash = (53 * hash) + getInfo().hashCode();
    hash = (37 * hash) + JSONPRATICA_FIELD_NUMBER;
    hash = (53 * hash) + getJsonPratica().hashCode();
    hash = (37 * hash) + OGGETTO_FIELD_NUMBER;
    hash = (53 * hash) + getOggetto().hashCode();
    hash = (37 * hash) + PROISTANZA_FIELD_NUMBER;
    hash = (53 * hash) + getProIstanza();
    hash = (37 * hash) + USERIDINS_FIELD_NUMBER;
    hash = (53 * hash) + getUseridIns().hashCode();
    hash = (37 * hash) + USERIDMOD_FIELD_NUMBER;
    hash = (53 * hash) + getUseridMod().hashCode();
    if (hasDtOraAnnullamento()) {
      hash = (37 * hash) + DTORAANNULLAMENTO_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraAnnullamento().hashCode();
    }
    if (hasUtente()) {
      hash = (37 * hash) + UTENTE_FIELD_NUMBER;
      hash = (53 * hash) + getUtente().hashCode();
    }
    if (getDocumentiCount() > 0) {
      hash = (37 * hash) + DOCUMENTI_FIELD_NUMBER;
      hash = (53 * hash) + getDocumentiList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Istanza parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gcalsolaro.grpc.artifact.model.Istanza prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Istanza}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gcalsolaro.grpc.artifact.model.Istanza)
      com.gcalsolaro.grpc.artifact.model.IstanzaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gcalsolaro.grpc.artifact.model.IstanzaOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Istanza_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gcalsolaro.grpc.artifact.model.IstanzaOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Istanza_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gcalsolaro.grpc.artifact.model.Istanza.class, com.gcalsolaro.grpc.artifact.model.Istanza.Builder.class);
    }

    // Construct using com.gcalsolaro.grpc.artifact.model.Istanza.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDocumentiFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      idIstanza_ = 0;

      archiviazione_ = "";

      cFiscale_ = "";

      cIstanza_ = "";

      denominazione_ = "";

      if (dtDomandaBuilder_ == null) {
        dtDomanda_ = null;
      } else {
        dtDomanda_ = null;
        dtDomandaBuilder_ = null;
      }
      if (dtOraAcquisizioneBuilder_ == null) {
        dtOraAcquisizione_ = null;
      } else {
        dtOraAcquisizione_ = null;
        dtOraAcquisizioneBuilder_ = null;
      }
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }
      info_ = "";

      jsonPratica_ = "";

      oggetto_ = "";

      proIstanza_ = 0;

      useridIns_ = "";

      useridMod_ = "";

      if (dtOraAnnullamentoBuilder_ == null) {
        dtOraAnnullamento_ = null;
      } else {
        dtOraAnnullamento_ = null;
        dtOraAnnullamentoBuilder_ = null;
      }
      if (utenteBuilder_ == null) {
        utente_ = null;
      } else {
        utente_ = null;
        utenteBuilder_ = null;
      }
      if (documentiBuilder_ == null) {
        documenti_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00020000);
      } else {
        documentiBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gcalsolaro.grpc.artifact.model.IstanzaOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Istanza_descriptor;
    }

    public com.gcalsolaro.grpc.artifact.model.Istanza getDefaultInstanceForType() {
      return com.gcalsolaro.grpc.artifact.model.Istanza.getDefaultInstance();
    }

    public com.gcalsolaro.grpc.artifact.model.Istanza build() {
      com.gcalsolaro.grpc.artifact.model.Istanza result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gcalsolaro.grpc.artifact.model.Istanza buildPartial() {
      com.gcalsolaro.grpc.artifact.model.Istanza result = new com.gcalsolaro.grpc.artifact.model.Istanza(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.idIstanza_ = idIstanza_;
      result.archiviazione_ = archiviazione_;
      result.cFiscale_ = cFiscale_;
      result.cIstanza_ = cIstanza_;
      result.denominazione_ = denominazione_;
      if (dtDomandaBuilder_ == null) {
        result.dtDomanda_ = dtDomanda_;
      } else {
        result.dtDomanda_ = dtDomandaBuilder_.build();
      }
      if (dtOraAcquisizioneBuilder_ == null) {
        result.dtOraAcquisizione_ = dtOraAcquisizione_;
      } else {
        result.dtOraAcquisizione_ = dtOraAcquisizioneBuilder_.build();
      }
      if (dtOraInsBuilder_ == null) {
        result.dtOraIns_ = dtOraIns_;
      } else {
        result.dtOraIns_ = dtOraInsBuilder_.build();
      }
      if (dtOraModBuilder_ == null) {
        result.dtOraMod_ = dtOraMod_;
      } else {
        result.dtOraMod_ = dtOraModBuilder_.build();
      }
      result.info_ = info_;
      result.jsonPratica_ = jsonPratica_;
      result.oggetto_ = oggetto_;
      result.proIstanza_ = proIstanza_;
      result.useridIns_ = useridIns_;
      result.useridMod_ = useridMod_;
      if (dtOraAnnullamentoBuilder_ == null) {
        result.dtOraAnnullamento_ = dtOraAnnullamento_;
      } else {
        result.dtOraAnnullamento_ = dtOraAnnullamentoBuilder_.build();
      }
      if (utenteBuilder_ == null) {
        result.utente_ = utente_;
      } else {
        result.utente_ = utenteBuilder_.build();
      }
      if (documentiBuilder_ == null) {
        if (((bitField0_ & 0x00020000) == 0x00020000)) {
          documenti_ = java.util.Collections.unmodifiableList(documenti_);
          bitField0_ = (bitField0_ & ~0x00020000);
        }
        result.documenti_ = documenti_;
      } else {
        result.documenti_ = documentiBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gcalsolaro.grpc.artifact.model.Istanza) {
        return mergeFrom((com.gcalsolaro.grpc.artifact.model.Istanza)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gcalsolaro.grpc.artifact.model.Istanza other) {
      if (other == com.gcalsolaro.grpc.artifact.model.Istanza.getDefaultInstance()) return this;
      if (other.getIdIstanza() != 0) {
        setIdIstanza(other.getIdIstanza());
      }
      if (!other.getArchiviazione().isEmpty()) {
        archiviazione_ = other.archiviazione_;
        onChanged();
      }
      if (!other.getCFiscale().isEmpty()) {
        cFiscale_ = other.cFiscale_;
        onChanged();
      }
      if (!other.getCIstanza().isEmpty()) {
        cIstanza_ = other.cIstanza_;
        onChanged();
      }
      if (!other.getDenominazione().isEmpty()) {
        denominazione_ = other.denominazione_;
        onChanged();
      }
      if (other.hasDtDomanda()) {
        mergeDtDomanda(other.getDtDomanda());
      }
      if (other.hasDtOraAcquisizione()) {
        mergeDtOraAcquisizione(other.getDtOraAcquisizione());
      }
      if (other.hasDtOraIns()) {
        mergeDtOraIns(other.getDtOraIns());
      }
      if (other.hasDtOraMod()) {
        mergeDtOraMod(other.getDtOraMod());
      }
      if (!other.getInfo().isEmpty()) {
        info_ = other.info_;
        onChanged();
      }
      if (!other.getJsonPratica().isEmpty()) {
        jsonPratica_ = other.jsonPratica_;
        onChanged();
      }
      if (!other.getOggetto().isEmpty()) {
        oggetto_ = other.oggetto_;
        onChanged();
      }
      if (other.getProIstanza() != 0) {
        setProIstanza(other.getProIstanza());
      }
      if (!other.getUseridIns().isEmpty()) {
        useridIns_ = other.useridIns_;
        onChanged();
      }
      if (!other.getUseridMod().isEmpty()) {
        useridMod_ = other.useridMod_;
        onChanged();
      }
      if (other.hasDtOraAnnullamento()) {
        mergeDtOraAnnullamento(other.getDtOraAnnullamento());
      }
      if (other.hasUtente()) {
        mergeUtente(other.getUtente());
      }
      if (documentiBuilder_ == null) {
        if (!other.documenti_.isEmpty()) {
          if (documenti_.isEmpty()) {
            documenti_ = other.documenti_;
            bitField0_ = (bitField0_ & ~0x00020000);
          } else {
            ensureDocumentiIsMutable();
            documenti_.addAll(other.documenti_);
          }
          onChanged();
        }
      } else {
        if (!other.documenti_.isEmpty()) {
          if (documentiBuilder_.isEmpty()) {
            documentiBuilder_.dispose();
            documentiBuilder_ = null;
            documenti_ = other.documenti_;
            bitField0_ = (bitField0_ & ~0x00020000);
            documentiBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDocumentiFieldBuilder() : null;
          } else {
            documentiBuilder_.addAllMessages(other.documenti_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gcalsolaro.grpc.artifact.model.Istanza parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gcalsolaro.grpc.artifact.model.Istanza) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int idIstanza_ ;
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public int getIdIstanza() {
      return idIstanza_;
    }
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public Builder setIdIstanza(int value) {
      
      idIstanza_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public Builder clearIdIstanza() {
      
      idIstanza_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object archiviazione_ = "";
    /**
     * <code>string archiviazione = 2;</code>
     */
    public java.lang.String getArchiviazione() {
      java.lang.Object ref = archiviazione_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        archiviazione_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string archiviazione = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArchiviazioneBytes() {
      java.lang.Object ref = archiviazione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        archiviazione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string archiviazione = 2;</code>
     */
    public Builder setArchiviazione(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      archiviazione_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string archiviazione = 2;</code>
     */
    public Builder clearArchiviazione() {
      
      archiviazione_ = getDefaultInstance().getArchiviazione();
      onChanged();
      return this;
    }
    /**
     * <code>string archiviazione = 2;</code>
     */
    public Builder setArchiviazioneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      archiviazione_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cFiscale_ = "";
    /**
     * <code>string cFiscale = 3;</code>
     */
    public java.lang.String getCFiscale() {
      java.lang.Object ref = cFiscale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cFiscale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCFiscaleBytes() {
      java.lang.Object ref = cFiscale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cFiscale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder setCFiscale(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cFiscale_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder clearCFiscale() {
      
      cFiscale_ = getDefaultInstance().getCFiscale();
      onChanged();
      return this;
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder setCFiscaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cFiscale_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cIstanza_ = "";
    /**
     * <code>string cIstanza = 4;</code>
     */
    public java.lang.String getCIstanza() {
      java.lang.Object ref = cIstanza_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cIstanza_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cIstanza = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCIstanzaBytes() {
      java.lang.Object ref = cIstanza_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cIstanza_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cIstanza = 4;</code>
     */
    public Builder setCIstanza(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cIstanza_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cIstanza = 4;</code>
     */
    public Builder clearCIstanza() {
      
      cIstanza_ = getDefaultInstance().getCIstanza();
      onChanged();
      return this;
    }
    /**
     * <code>string cIstanza = 4;</code>
     */
    public Builder setCIstanzaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cIstanza_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object denominazione_ = "";
    /**
     * <code>string denominazione = 5;</code>
     */
    public java.lang.String getDenominazione() {
      java.lang.Object ref = denominazione_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        denominazione_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string denominazione = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDenominazioneBytes() {
      java.lang.Object ref = denominazione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        denominazione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string denominazione = 5;</code>
     */
    public Builder setDenominazione(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      denominazione_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string denominazione = 5;</code>
     */
    public Builder clearDenominazione() {
      
      denominazione_ = getDefaultInstance().getDenominazione();
      onChanged();
      return this;
    }
    /**
     * <code>string denominazione = 5;</code>
     */
    public Builder setDenominazioneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      denominazione_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dtDomanda_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtDomandaBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public boolean hasDtDomanda() {
      return dtDomandaBuilder_ != null || dtDomanda_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public com.google.protobuf.Timestamp getDtDomanda() {
      if (dtDomandaBuilder_ == null) {
        return dtDomanda_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtDomanda_;
      } else {
        return dtDomandaBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public Builder setDtDomanda(com.google.protobuf.Timestamp value) {
      if (dtDomandaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtDomanda_ = value;
        onChanged();
      } else {
        dtDomandaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public Builder setDtDomanda(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtDomandaBuilder_ == null) {
        dtDomanda_ = builderForValue.build();
        onChanged();
      } else {
        dtDomandaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public Builder mergeDtDomanda(com.google.protobuf.Timestamp value) {
      if (dtDomandaBuilder_ == null) {
        if (dtDomanda_ != null) {
          dtDomanda_ =
            com.google.protobuf.Timestamp.newBuilder(dtDomanda_).mergeFrom(value).buildPartial();
        } else {
          dtDomanda_ = value;
        }
        onChanged();
      } else {
        dtDomandaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public Builder clearDtDomanda() {
      if (dtDomandaBuilder_ == null) {
        dtDomanda_ = null;
        onChanged();
      } else {
        dtDomanda_ = null;
        dtDomandaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtDomandaBuilder() {
      
      onChanged();
      return getDtDomandaFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtDomandaOrBuilder() {
      if (dtDomandaBuilder_ != null) {
        return dtDomandaBuilder_.getMessageOrBuilder();
      } else {
        return dtDomanda_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtDomanda_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtDomandaFieldBuilder() {
      if (dtDomandaBuilder_ == null) {
        dtDomandaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtDomanda(),
                getParentForChildren(),
                isClean());
        dtDomanda_ = null;
      }
      return dtDomandaBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraAcquisizione_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraAcquisizioneBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public boolean hasDtOraAcquisizione() {
      return dtOraAcquisizioneBuilder_ != null || dtOraAcquisizione_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public com.google.protobuf.Timestamp getDtOraAcquisizione() {
      if (dtOraAcquisizioneBuilder_ == null) {
        return dtOraAcquisizione_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAcquisizione_;
      } else {
        return dtOraAcquisizioneBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public Builder setDtOraAcquisizione(com.google.protobuf.Timestamp value) {
      if (dtOraAcquisizioneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraAcquisizione_ = value;
        onChanged();
      } else {
        dtOraAcquisizioneBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public Builder setDtOraAcquisizione(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraAcquisizioneBuilder_ == null) {
        dtOraAcquisizione_ = builderForValue.build();
        onChanged();
      } else {
        dtOraAcquisizioneBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public Builder mergeDtOraAcquisizione(com.google.protobuf.Timestamp value) {
      if (dtOraAcquisizioneBuilder_ == null) {
        if (dtOraAcquisizione_ != null) {
          dtOraAcquisizione_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraAcquisizione_).mergeFrom(value).buildPartial();
        } else {
          dtOraAcquisizione_ = value;
        }
        onChanged();
      } else {
        dtOraAcquisizioneBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public Builder clearDtOraAcquisizione() {
      if (dtOraAcquisizioneBuilder_ == null) {
        dtOraAcquisizione_ = null;
        onChanged();
      } else {
        dtOraAcquisizione_ = null;
        dtOraAcquisizioneBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraAcquisizioneBuilder() {
      
      onChanged();
      return getDtOraAcquisizioneFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraAcquisizioneOrBuilder() {
      if (dtOraAcquisizioneBuilder_ != null) {
        return dtOraAcquisizioneBuilder_.getMessageOrBuilder();
      } else {
        return dtOraAcquisizione_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAcquisizione_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraAcquisizioneFieldBuilder() {
      if (dtOraAcquisizioneBuilder_ == null) {
        dtOraAcquisizioneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraAcquisizione(),
                getParentForChildren(),
                isClean());
        dtOraAcquisizione_ = null;
      }
      return dtOraAcquisizioneBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraIns_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraInsBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public boolean hasDtOraIns() {
      return dtOraInsBuilder_ != null || dtOraIns_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public com.google.protobuf.Timestamp getDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      } else {
        return dtOraInsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public Builder setDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraIns_ = value;
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public Builder setDtOraIns(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = builderForValue.build();
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public Builder mergeDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (dtOraIns_ != null) {
          dtOraIns_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraIns_).mergeFrom(value).buildPartial();
        } else {
          dtOraIns_ = value;
        }
        onChanged();
      } else {
        dtOraInsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public Builder clearDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
        onChanged();
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraInsBuilder() {
      
      onChanged();
      return getDtOraInsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
      if (dtOraInsBuilder_ != null) {
        return dtOraInsBuilder_.getMessageOrBuilder();
      } else {
        return dtOraIns_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraInsFieldBuilder() {
      if (dtOraInsBuilder_ == null) {
        dtOraInsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraIns(),
                getParentForChildren(),
                isClean());
        dtOraIns_ = null;
      }
      return dtOraInsBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraMod_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraModBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public boolean hasDtOraMod() {
      return dtOraModBuilder_ != null || dtOraMod_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public com.google.protobuf.Timestamp getDtOraMod() {
      if (dtOraModBuilder_ == null) {
        return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      } else {
        return dtOraModBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public Builder setDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraMod_ = value;
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public Builder setDtOraMod(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = builderForValue.build();
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public Builder mergeDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (dtOraMod_ != null) {
          dtOraMod_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraMod_).mergeFrom(value).buildPartial();
        } else {
          dtOraMod_ = value;
        }
        onChanged();
      } else {
        dtOraModBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public Builder clearDtOraMod() {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
        onChanged();
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraModBuilder() {
      
      onChanged();
      return getDtOraModFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
      if (dtOraModBuilder_ != null) {
        return dtOraModBuilder_.getMessageOrBuilder();
      } else {
        return dtOraMod_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraModFieldBuilder() {
      if (dtOraModBuilder_ == null) {
        dtOraModBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraMod(),
                getParentForChildren(),
                isClean());
        dtOraMod_ = null;
      }
      return dtOraModBuilder_;
    }

    private java.lang.Object info_ = "";
    /**
     * <code>string info = 10;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string info = 10;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string info = 10;</code>
     */
    public Builder setInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      info_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string info = 10;</code>
     */
    public Builder clearInfo() {
      
      info_ = getDefaultInstance().getInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string info = 10;</code>
     */
    public Builder setInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      info_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jsonPratica_ = "";
    /**
     * <code>string jsonPratica = 11;</code>
     */
    public java.lang.String getJsonPratica() {
      java.lang.Object ref = jsonPratica_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonPratica_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jsonPratica = 11;</code>
     */
    public com.google.protobuf.ByteString
        getJsonPraticaBytes() {
      java.lang.Object ref = jsonPratica_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonPratica_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonPratica = 11;</code>
     */
    public Builder setJsonPratica(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonPratica_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonPratica = 11;</code>
     */
    public Builder clearJsonPratica() {
      
      jsonPratica_ = getDefaultInstance().getJsonPratica();
      onChanged();
      return this;
    }
    /**
     * <code>string jsonPratica = 11;</code>
     */
    public Builder setJsonPraticaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonPratica_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object oggetto_ = "";
    /**
     * <code>string oggetto = 12;</code>
     */
    public java.lang.String getOggetto() {
      java.lang.Object ref = oggetto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oggetto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oggetto = 12;</code>
     */
    public com.google.protobuf.ByteString
        getOggettoBytes() {
      java.lang.Object ref = oggetto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oggetto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oggetto = 12;</code>
     */
    public Builder setOggetto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oggetto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oggetto = 12;</code>
     */
    public Builder clearOggetto() {
      
      oggetto_ = getDefaultInstance().getOggetto();
      onChanged();
      return this;
    }
    /**
     * <code>string oggetto = 12;</code>
     */
    public Builder setOggettoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oggetto_ = value;
      onChanged();
      return this;
    }

    private int proIstanza_ ;
    /**
     * <code>int32 proIstanza = 13;</code>
     */
    public int getProIstanza() {
      return proIstanza_;
    }
    /**
     * <code>int32 proIstanza = 13;</code>
     */
    public Builder setProIstanza(int value) {
      
      proIstanza_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 proIstanza = 13;</code>
     */
    public Builder clearProIstanza() {
      
      proIstanza_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object useridIns_ = "";
    /**
     * <code>string useridIns = 14;</code>
     */
    public java.lang.String getUseridIns() {
      java.lang.Object ref = useridIns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridIns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUseridInsBytes() {
      java.lang.Object ref = useridIns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridIns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder setUseridIns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridIns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder clearUseridIns() {
      
      useridIns_ = getDefaultInstance().getUseridIns();
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder setUseridInsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridIns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridMod_ = "";
    /**
     * <code>string useridMod = 15;</code>
     */
    public java.lang.String getUseridMod() {
      java.lang.Object ref = useridMod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridMod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public com.google.protobuf.ByteString
        getUseridModBytes() {
      java.lang.Object ref = useridMod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridMod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder setUseridMod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridMod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder clearUseridMod() {
      
      useridMod_ = getDefaultInstance().getUseridMod();
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder setUseridModBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridMod_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dtOraAnnullamento_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraAnnullamentoBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public boolean hasDtOraAnnullamento() {
      return dtOraAnnullamentoBuilder_ != null || dtOraAnnullamento_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public com.google.protobuf.Timestamp getDtOraAnnullamento() {
      if (dtOraAnnullamentoBuilder_ == null) {
        return dtOraAnnullamento_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAnnullamento_;
      } else {
        return dtOraAnnullamentoBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public Builder setDtOraAnnullamento(com.google.protobuf.Timestamp value) {
      if (dtOraAnnullamentoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraAnnullamento_ = value;
        onChanged();
      } else {
        dtOraAnnullamentoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public Builder setDtOraAnnullamento(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraAnnullamentoBuilder_ == null) {
        dtOraAnnullamento_ = builderForValue.build();
        onChanged();
      } else {
        dtOraAnnullamentoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public Builder mergeDtOraAnnullamento(com.google.protobuf.Timestamp value) {
      if (dtOraAnnullamentoBuilder_ == null) {
        if (dtOraAnnullamento_ != null) {
          dtOraAnnullamento_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraAnnullamento_).mergeFrom(value).buildPartial();
        } else {
          dtOraAnnullamento_ = value;
        }
        onChanged();
      } else {
        dtOraAnnullamentoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public Builder clearDtOraAnnullamento() {
      if (dtOraAnnullamentoBuilder_ == null) {
        dtOraAnnullamento_ = null;
        onChanged();
      } else {
        dtOraAnnullamento_ = null;
        dtOraAnnullamentoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraAnnullamentoBuilder() {
      
      onChanged();
      return getDtOraAnnullamentoFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraAnnullamentoOrBuilder() {
      if (dtOraAnnullamentoBuilder_ != null) {
        return dtOraAnnullamentoBuilder_.getMessageOrBuilder();
      } else {
        return dtOraAnnullamento_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraAnnullamento_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraAnnullamentoFieldBuilder() {
      if (dtOraAnnullamentoBuilder_ == null) {
        dtOraAnnullamentoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraAnnullamento(),
                getParentForChildren(),
                isClean());
        dtOraAnnullamento_ = null;
      }
      return dtOraAnnullamentoBuilder_;
    }

    private com.gcalsolaro.grpc.artifact.model.Utente utente_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Utente, com.gcalsolaro.grpc.artifact.model.Utente.Builder, com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder> utenteBuilder_;
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public boolean hasUtente() {
      return utenteBuilder_ != null || utente_ != null;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Utente getUtente() {
      if (utenteBuilder_ == null) {
        return utente_ == null ? com.gcalsolaro.grpc.artifact.model.Utente.getDefaultInstance() : utente_;
      } else {
        return utenteBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public Builder setUtente(com.gcalsolaro.grpc.artifact.model.Utente value) {
      if (utenteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        utente_ = value;
        onChanged();
      } else {
        utenteBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public Builder setUtente(
        com.gcalsolaro.grpc.artifact.model.Utente.Builder builderForValue) {
      if (utenteBuilder_ == null) {
        utente_ = builderForValue.build();
        onChanged();
      } else {
        utenteBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public Builder mergeUtente(com.gcalsolaro.grpc.artifact.model.Utente value) {
      if (utenteBuilder_ == null) {
        if (utente_ != null) {
          utente_ =
            com.gcalsolaro.grpc.artifact.model.Utente.newBuilder(utente_).mergeFrom(value).buildPartial();
        } else {
          utente_ = value;
        }
        onChanged();
      } else {
        utenteBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public Builder clearUtente() {
      if (utenteBuilder_ == null) {
        utente_ = null;
        onChanged();
      } else {
        utente_ = null;
        utenteBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Utente.Builder getUtenteBuilder() {
      
      onChanged();
      return getUtenteFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder getUtenteOrBuilder() {
      if (utenteBuilder_ != null) {
        return utenteBuilder_.getMessageOrBuilder();
      } else {
        return utente_ == null ?
            com.gcalsolaro.grpc.artifact.model.Utente.getDefaultInstance() : utente_;
      }
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Utente, com.gcalsolaro.grpc.artifact.model.Utente.Builder, com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder> 
        getUtenteFieldBuilder() {
      if (utenteBuilder_ == null) {
        utenteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gcalsolaro.grpc.artifact.model.Utente, com.gcalsolaro.grpc.artifact.model.Utente.Builder, com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder>(
                getUtente(),
                getParentForChildren(),
                isClean());
        utente_ = null;
      }
      return utenteBuilder_;
    }

    private java.util.List<com.gcalsolaro.grpc.artifact.model.Documento> documenti_ =
      java.util.Collections.emptyList();
    private void ensureDocumentiIsMutable() {
      if (!((bitField0_ & 0x00020000) == 0x00020000)) {
        documenti_ = new java.util.ArrayList<com.gcalsolaro.grpc.artifact.model.Documento>(documenti_);
        bitField0_ |= 0x00020000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Documento, com.gcalsolaro.grpc.artifact.model.Documento.Builder, com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder> documentiBuilder_;

    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public java.util.List<com.gcalsolaro.grpc.artifact.model.Documento> getDocumentiList() {
      if (documentiBuilder_ == null) {
        return java.util.Collections.unmodifiableList(documenti_);
      } else {
        return documentiBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public int getDocumentiCount() {
      if (documentiBuilder_ == null) {
        return documenti_.size();
      } else {
        return documentiBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Documento getDocumenti(int index) {
      if (documentiBuilder_ == null) {
        return documenti_.get(index);
      } else {
        return documentiBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder setDocumenti(
        int index, com.gcalsolaro.grpc.artifact.model.Documento value) {
      if (documentiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentiIsMutable();
        documenti_.set(index, value);
        onChanged();
      } else {
        documentiBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder setDocumenti(
        int index, com.gcalsolaro.grpc.artifact.model.Documento.Builder builderForValue) {
      if (documentiBuilder_ == null) {
        ensureDocumentiIsMutable();
        documenti_.set(index, builderForValue.build());
        onChanged();
      } else {
        documentiBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder addDocumenti(com.gcalsolaro.grpc.artifact.model.Documento value) {
      if (documentiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentiIsMutable();
        documenti_.add(value);
        onChanged();
      } else {
        documentiBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder addDocumenti(
        int index, com.gcalsolaro.grpc.artifact.model.Documento value) {
      if (documentiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDocumentiIsMutable();
        documenti_.add(index, value);
        onChanged();
      } else {
        documentiBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder addDocumenti(
        com.gcalsolaro.grpc.artifact.model.Documento.Builder builderForValue) {
      if (documentiBuilder_ == null) {
        ensureDocumentiIsMutable();
        documenti_.add(builderForValue.build());
        onChanged();
      } else {
        documentiBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder addDocumenti(
        int index, com.gcalsolaro.grpc.artifact.model.Documento.Builder builderForValue) {
      if (documentiBuilder_ == null) {
        ensureDocumentiIsMutable();
        documenti_.add(index, builderForValue.build());
        onChanged();
      } else {
        documentiBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder addAllDocumenti(
        java.lang.Iterable<? extends com.gcalsolaro.grpc.artifact.model.Documento> values) {
      if (documentiBuilder_ == null) {
        ensureDocumentiIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, documenti_);
        onChanged();
      } else {
        documentiBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder clearDocumenti() {
      if (documentiBuilder_ == null) {
        documenti_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00020000);
        onChanged();
      } else {
        documentiBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public Builder removeDocumenti(int index) {
      if (documentiBuilder_ == null) {
        ensureDocumentiIsMutable();
        documenti_.remove(index);
        onChanged();
      } else {
        documentiBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Documento.Builder getDocumentiBuilder(
        int index) {
      return getDocumentiFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder getDocumentiOrBuilder(
        int index) {
      if (documentiBuilder_ == null) {
        return documenti_.get(index);  } else {
        return documentiBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public java.util.List<? extends com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder> 
         getDocumentiOrBuilderList() {
      if (documentiBuilder_ != null) {
        return documentiBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(documenti_);
      }
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Documento.Builder addDocumentiBuilder() {
      return getDocumentiFieldBuilder().addBuilder(
          com.gcalsolaro.grpc.artifact.model.Documento.getDefaultInstance());
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Documento.Builder addDocumentiBuilder(
        int index) {
      return getDocumentiFieldBuilder().addBuilder(
          index, com.gcalsolaro.grpc.artifact.model.Documento.getDefaultInstance());
    }
    /**
     * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
     */
    public java.util.List<com.gcalsolaro.grpc.artifact.model.Documento.Builder> 
         getDocumentiBuilderList() {
      return getDocumentiFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Documento, com.gcalsolaro.grpc.artifact.model.Documento.Builder, com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder> 
        getDocumentiFieldBuilder() {
      if (documentiBuilder_ == null) {
        documentiBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.gcalsolaro.grpc.artifact.model.Documento, com.gcalsolaro.grpc.artifact.model.Documento.Builder, com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder>(
                documenti_,
                ((bitField0_ & 0x00020000) == 0x00020000),
                getParentForChildren(),
                isClean());
        documenti_ = null;
      }
      return documentiBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gcalsolaro.grpc.artifact.model.Istanza)
  }

  // @@protoc_insertion_point(class_scope:com.gcalsolaro.grpc.artifact.model.Istanza)
  private static final com.gcalsolaro.grpc.artifact.model.Istanza DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gcalsolaro.grpc.artifact.model.Istanza();
  }

  public static com.gcalsolaro.grpc.artifact.model.Istanza getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Istanza>
      PARSER = new com.google.protobuf.AbstractParser<Istanza>() {
    public Istanza parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Istanza(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Istanza> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Istanza> getParserForType() {
    return PARSER;
  }

  public com.gcalsolaro.grpc.artifact.model.Istanza getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

