// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.gcalsolaro.grpc.artifact.model;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.model.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idUser = 1;</code>
   */
  int getIdUser();

  /**
   * <code>string fiscalCode = 2;</code>
   */
  java.lang.String getFiscalCode();
  /**
   * <code>string fiscalCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getFiscalCodeBytes();

  /**
   * <code>string surname = 3;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 3;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string name = 5;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
