// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Utente.proto

package com.gcalsolaro.grpc.artifact.model;

public final class UtenteOuterClass {
  private UtenteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gcalsolaro_grpc_artifact_model_Utente_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Utente.proto\022\"com.gcalsolaro.grpc.arti" +
      "fact.model\032\037google/protobuf/timestamp.pr" +
      "oto\"\211\003\n\006Utente\022\020\n\010idUtente\030\001 \001(\005\022\017\n\007cCom" +
      "une\030\002 \001(\t\022\020\n\010cFiscale\030\003 \001(\t\022\017\n\007cognome\030\004" +
      " \001(\t\022\031\n\021descrizioneComune\030\005 \001(\t\022-\n\tdtNas" +
      "cita\030\006 \001(\0132\032.google.protobuf.Timestamp\022," +
      "\n\010dtOraIns\030\007 \001(\0132\032.google.protobuf.Times" +
      "tamp\022,\n\010dtOraMod\030\010 \001(\0132\032.google.protobuf" +
      ".Timestamp\0223\n\017dtRegistrazione\030\t \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\r\n\005email\030\n \001(\t\022\014",
      "\n\004nome\030\013 \001(\t\022\014\n\004prov\030\014 \001(\t\022\r\n\005stato\030\r \001(" +
      "\t\022\021\n\tuseridIns\030\016 \001(\t\022\021\n\tuseridMod\030\017 \001(\tB" +
      "\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gcalsolaro_grpc_artifact_model_Utente_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor,
        new java.lang.String[] { "IdUtente", "CComune", "CFiscale", "Cognome", "DescrizioneComune", "DtNascita", "DtOraIns", "DtOraMod", "DtRegistrazione", "Email", "Nome", "Prov", "Stato", "UseridIns", "UseridMod", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
