// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Documento.proto

package com.gcalsolaro.grpc.artifact.model;

public final class DocumentoOuterClass {
  private DocumentoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gcalsolaro_grpc_artifact_model_Documento_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Documento.proto\022\"com.gcalsolaro.grpc.a" +
      "rtifact.model\032\037google/protobuf/timestamp" +
      ".proto\"\326\002\n\tDocumento\022\023\n\013idDocumento\030\001 \001(" +
      "\005\022\023\n\013descrizione\030\002 \001(\t\0220\n\014dtOraCancRec\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\022,\n\010dtOr" +
      "aIns\030\004 \001(\0132\032.google.protobuf.Timestamp\022," +
      "\n\010dtOraMod\030\005 \001(\0132\032.google.protobuf.Times" +
      "tamp\022\020\n\010nomeFile\030\006 \001(\t\022\020\n\010pathFile\030\007 \001(\t" +
      "\022\017\n\007pathTmp\030\010 \001(\t\022\025\n\ruseridCancRec\030\t \001(\t" +
      "\022\021\n\tuseridIns\030\n \001(\t\022\021\n\tuseridMod\030\013 \001(\t\022\r",
      "\n\005stato\030\014 \001(\t\022\020\n\010checksum\030\r \001(\tB\002P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gcalsolaro_grpc_artifact_model_Documento_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gcalsolaro_grpc_artifact_model_Documento_descriptor,
        new java.lang.String[] { "IdDocumento", "Descrizione", "DtOraCancRec", "DtOraIns", "DtOraMod", "NomeFile", "PathFile", "PathTmp", "UseridCancRec", "UseridIns", "UseridMod", "Stato", "Checksum", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
