// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Instance.proto

package com.gcalsolaro.grpc.artifact.model;

public final class InstanceOuterClass {
  private InstanceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gcalsolaro_grpc_artifact_model_Instance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gcalsolaro_grpc_artifact_model_Instance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Instance.proto\022\"com.gcalsolaro.grpc.ar" +
      "tifact.model\032\nUser.proto\"w\n\010Instance\022\022\n\n" +
      "idInstance\030\001 \001(\005\022\021\n\tcInstance\030\002 \001(\t\022\014\n\004i" +
      "nfo\030\n \001(\t\0226\n\004user\030\021 \001(\0132(.com.gcalsolaro" +
      ".grpc.artifact.model.UserB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gcalsolaro.grpc.artifact.model.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_gcalsolaro_grpc_artifact_model_Instance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gcalsolaro_grpc_artifact_model_Instance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gcalsolaro_grpc_artifact_model_Instance_descriptor,
        new java.lang.String[] { "IdInstance", "CInstance", "Info", "User", });
    com.gcalsolaro.grpc.artifact.model.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
