// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Istanza.proto

package com.gcalsolaro.grpc.artifact.model;

public interface IstanzaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.model.Istanza)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idIstanza = 1;</code>
   */
  int getIdIstanza();

  /**
   * <code>string archiviazione = 2;</code>
   */
  java.lang.String getArchiviazione();
  /**
   * <code>string archiviazione = 2;</code>
   */
  com.google.protobuf.ByteString
      getArchiviazioneBytes();

  /**
   * <code>string cFiscale = 3;</code>
   */
  java.lang.String getCFiscale();
  /**
   * <code>string cFiscale = 3;</code>
   */
  com.google.protobuf.ByteString
      getCFiscaleBytes();

  /**
   * <code>string cIstanza = 4;</code>
   */
  java.lang.String getCIstanza();
  /**
   * <code>string cIstanza = 4;</code>
   */
  com.google.protobuf.ByteString
      getCIstanzaBytes();

  /**
   * <code>string denominazione = 5;</code>
   */
  java.lang.String getDenominazione();
  /**
   * <code>string denominazione = 5;</code>
   */
  com.google.protobuf.ByteString
      getDenominazioneBytes();

  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  boolean hasDtDomanda();
  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  com.google.protobuf.Timestamp getDtDomanda();
  /**
   * <code>.google.protobuf.Timestamp dtDomanda = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtDomandaOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  boolean hasDtOraAcquisizione();
  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  com.google.protobuf.Timestamp getDtOraAcquisizione();
  /**
   * <code>.google.protobuf.Timestamp dtOraAcquisizione = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraAcquisizioneOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  boolean hasDtOraIns();
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  com.google.protobuf.Timestamp getDtOraIns();
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  boolean hasDtOraMod();
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  com.google.protobuf.Timestamp getDtOraMod();
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder();

  /**
   * <code>string info = 10;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 10;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>string jsonPratica = 11;</code>
   */
  java.lang.String getJsonPratica();
  /**
   * <code>string jsonPratica = 11;</code>
   */
  com.google.protobuf.ByteString
      getJsonPraticaBytes();

  /**
   * <code>string oggetto = 12;</code>
   */
  java.lang.String getOggetto();
  /**
   * <code>string oggetto = 12;</code>
   */
  com.google.protobuf.ByteString
      getOggettoBytes();

  /**
   * <code>int32 proIstanza = 13;</code>
   */
  int getProIstanza();

  /**
   * <code>string useridIns = 14;</code>
   */
  java.lang.String getUseridIns();
  /**
   * <code>string useridIns = 14;</code>
   */
  com.google.protobuf.ByteString
      getUseridInsBytes();

  /**
   * <code>string useridMod = 15;</code>
   */
  java.lang.String getUseridMod();
  /**
   * <code>string useridMod = 15;</code>
   */
  com.google.protobuf.ByteString
      getUseridModBytes();

  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  boolean hasDtOraAnnullamento();
  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  com.google.protobuf.Timestamp getDtOraAnnullamento();
  /**
   * <code>.google.protobuf.Timestamp dtOraAnnullamento = 16;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDtOraAnnullamentoOrBuilder();

  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  boolean hasUtente();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  com.gcalsolaro.grpc.artifact.model.Utente getUtente();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Utente utente = 17;</code>
   */
  com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder getUtenteOrBuilder();

  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  java.util.List<com.gcalsolaro.grpc.artifact.model.Documento> 
      getDocumentiList();
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  com.gcalsolaro.grpc.artifact.model.Documento getDocumenti(int index);
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  int getDocumentiCount();
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  java.util.List<? extends com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder> 
      getDocumentiOrBuilderList();
  /**
   * <code>repeated .com.gcalsolaro.grpc.artifact.model.Documento documenti = 18;</code>
   */
  com.gcalsolaro.grpc.artifact.model.DocumentoOrBuilder getDocumentiOrBuilder(
      int index);
}
