// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Utente.proto

package com.gcalsolaro.grpc.artifact.model;

/**
 * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Utente}
 */
public  final class Utente extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gcalsolaro.grpc.artifact.model.Utente)
    UtenteOrBuilder {
  // Use Utente.newBuilder() to construct.
  private Utente(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Utente() {
    idUtente_ = 0;
    cComune_ = "";
    cFiscale_ = "";
    cognome_ = "";
    descrizioneComune_ = "";
    email_ = "";
    nome_ = "";
    prov_ = "";
    stato_ = "";
    useridIns_ = "";
    useridMod_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Utente(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            idUtente_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cComune_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cFiscale_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cognome_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            descrizioneComune_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtNascita_ != null) {
              subBuilder = dtNascita_.toBuilder();
            }
            dtNascita_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtNascita_);
              dtNascita_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraIns_ != null) {
              subBuilder = dtOraIns_.toBuilder();
            }
            dtOraIns_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraIns_);
              dtOraIns_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtOraMod_ != null) {
              subBuilder = dtOraMod_.toBuilder();
            }
            dtOraMod_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtOraMod_);
              dtOraMod_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dtRegistrazione_ != null) {
              subBuilder = dtRegistrazione_.toBuilder();
            }
            dtRegistrazione_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dtRegistrazione_);
              dtRegistrazione_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            nome_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            prov_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            stato_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            useridIns_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            useridMod_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gcalsolaro.grpc.artifact.model.UtenteOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gcalsolaro.grpc.artifact.model.UtenteOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Utente_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gcalsolaro.grpc.artifact.model.Utente.class, com.gcalsolaro.grpc.artifact.model.Utente.Builder.class);
  }

  public static final int IDUTENTE_FIELD_NUMBER = 1;
  private int idUtente_;
  /**
   * <code>int32 idUtente = 1;</code>
   */
  public int getIdUtente() {
    return idUtente_;
  }

  public static final int CCOMUNE_FIELD_NUMBER = 2;
  private volatile java.lang.Object cComune_;
  /**
   * <code>string cComune = 2;</code>
   */
  public java.lang.String getCComune() {
    java.lang.Object ref = cComune_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cComune_ = s;
      return s;
    }
  }
  /**
   * <code>string cComune = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCComuneBytes() {
    java.lang.Object ref = cComune_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cComune_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CFISCALE_FIELD_NUMBER = 3;
  private volatile java.lang.Object cFiscale_;
  /**
   * <code>string cFiscale = 3;</code>
   */
  public java.lang.String getCFiscale() {
    java.lang.Object ref = cFiscale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cFiscale_ = s;
      return s;
    }
  }
  /**
   * <code>string cFiscale = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCFiscaleBytes() {
    java.lang.Object ref = cFiscale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cFiscale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COGNOME_FIELD_NUMBER = 4;
  private volatile java.lang.Object cognome_;
  /**
   * <code>string cognome = 4;</code>
   */
  public java.lang.String getCognome() {
    java.lang.Object ref = cognome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cognome_ = s;
      return s;
    }
  }
  /**
   * <code>string cognome = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCognomeBytes() {
    java.lang.Object ref = cognome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cognome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIZIONECOMUNE_FIELD_NUMBER = 5;
  private volatile java.lang.Object descrizioneComune_;
  /**
   * <code>string descrizioneComune = 5;</code>
   */
  public java.lang.String getDescrizioneComune() {
    java.lang.Object ref = descrizioneComune_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      descrizioneComune_ = s;
      return s;
    }
  }
  /**
   * <code>string descrizioneComune = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDescrizioneComuneBytes() {
    java.lang.Object ref = descrizioneComune_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      descrizioneComune_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DTNASCITA_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp dtNascita_;
  /**
   * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
   */
  public boolean hasDtNascita() {
    return dtNascita_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
   */
  public com.google.protobuf.Timestamp getDtNascita() {
    return dtNascita_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtNascita_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtNascitaOrBuilder() {
    return getDtNascita();
  }

  public static final int DTORAINS_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp dtOraIns_;
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
   */
  public boolean hasDtOraIns() {
    return dtOraIns_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
   */
  public com.google.protobuf.Timestamp getDtOraIns() {
    return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
    return getDtOraIns();
  }

  public static final int DTORAMOD_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp dtOraMod_;
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
   */
  public boolean hasDtOraMod() {
    return dtOraMod_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
   */
  public com.google.protobuf.Timestamp getDtOraMod() {
    return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
    return getDtOraMod();
  }

  public static final int DTREGISTRAZIONE_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp dtRegistrazione_;
  /**
   * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
   */
  public boolean hasDtRegistrazione() {
    return dtRegistrazione_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
   */
  public com.google.protobuf.Timestamp getDtRegistrazione() {
    return dtRegistrazione_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtRegistrazione_;
  }
  /**
   * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDtRegistrazioneOrBuilder() {
    return getDtRegistrazione();
  }

  public static final int EMAIL_FIELD_NUMBER = 10;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 10;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 10;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_FIELD_NUMBER = 11;
  private volatile java.lang.Object nome_;
  /**
   * <code>string nome = 11;</code>
   */
  public java.lang.String getNome() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nome_ = s;
      return s;
    }
  }
  /**
   * <code>string nome = 11;</code>
   */
  public com.google.protobuf.ByteString
      getNomeBytes() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROV_FIELD_NUMBER = 12;
  private volatile java.lang.Object prov_;
  /**
   * <code>string prov = 12;</code>
   */
  public java.lang.String getProv() {
    java.lang.Object ref = prov_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prov_ = s;
      return s;
    }
  }
  /**
   * <code>string prov = 12;</code>
   */
  public com.google.protobuf.ByteString
      getProvBytes() {
    java.lang.Object ref = prov_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prov_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATO_FIELD_NUMBER = 13;
  private volatile java.lang.Object stato_;
  /**
   * <code>string stato = 13;</code>
   */
  public java.lang.String getStato() {
    java.lang.Object ref = stato_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stato_ = s;
      return s;
    }
  }
  /**
   * <code>string stato = 13;</code>
   */
  public com.google.protobuf.ByteString
      getStatoBytes() {
    java.lang.Object ref = stato_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stato_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDINS_FIELD_NUMBER = 14;
  private volatile java.lang.Object useridIns_;
  /**
   * <code>string useridIns = 14;</code>
   */
  public java.lang.String getUseridIns() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridIns_ = s;
      return s;
    }
  }
  /**
   * <code>string useridIns = 14;</code>
   */
  public com.google.protobuf.ByteString
      getUseridInsBytes() {
    java.lang.Object ref = useridIns_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridIns_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERIDMOD_FIELD_NUMBER = 15;
  private volatile java.lang.Object useridMod_;
  /**
   * <code>string useridMod = 15;</code>
   */
  public java.lang.String getUseridMod() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      useridMod_ = s;
      return s;
    }
  }
  /**
   * <code>string useridMod = 15;</code>
   */
  public com.google.protobuf.ByteString
      getUseridModBytes() {
    java.lang.Object ref = useridMod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      useridMod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idUtente_ != 0) {
      output.writeInt32(1, idUtente_);
    }
    if (!getCComuneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cComune_);
    }
    if (!getCFiscaleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cFiscale_);
    }
    if (!getCognomeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cognome_);
    }
    if (!getDescrizioneComuneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, descrizioneComune_);
    }
    if (dtNascita_ != null) {
      output.writeMessage(6, getDtNascita());
    }
    if (dtOraIns_ != null) {
      output.writeMessage(7, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      output.writeMessage(8, getDtOraMod());
    }
    if (dtRegistrazione_ != null) {
      output.writeMessage(9, getDtRegistrazione());
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, email_);
    }
    if (!getNomeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, nome_);
    }
    if (!getProvBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, prov_);
    }
    if (!getStatoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, stato_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, useridMod_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idUtente_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idUtente_);
    }
    if (!getCComuneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cComune_);
    }
    if (!getCFiscaleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cFiscale_);
    }
    if (!getCognomeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cognome_);
    }
    if (!getDescrizioneComuneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, descrizioneComune_);
    }
    if (dtNascita_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDtNascita());
    }
    if (dtOraIns_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDtOraIns());
    }
    if (dtOraMod_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDtOraMod());
    }
    if (dtRegistrazione_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDtRegistrazione());
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, email_);
    }
    if (!getNomeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, nome_);
    }
    if (!getProvBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, prov_);
    }
    if (!getStatoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, stato_);
    }
    if (!getUseridInsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, useridIns_);
    }
    if (!getUseridModBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, useridMod_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gcalsolaro.grpc.artifact.model.Utente)) {
      return super.equals(obj);
    }
    com.gcalsolaro.grpc.artifact.model.Utente other = (com.gcalsolaro.grpc.artifact.model.Utente) obj;

    boolean result = true;
    result = result && (getIdUtente()
        == other.getIdUtente());
    result = result && getCComune()
        .equals(other.getCComune());
    result = result && getCFiscale()
        .equals(other.getCFiscale());
    result = result && getCognome()
        .equals(other.getCognome());
    result = result && getDescrizioneComune()
        .equals(other.getDescrizioneComune());
    result = result && (hasDtNascita() == other.hasDtNascita());
    if (hasDtNascita()) {
      result = result && getDtNascita()
          .equals(other.getDtNascita());
    }
    result = result && (hasDtOraIns() == other.hasDtOraIns());
    if (hasDtOraIns()) {
      result = result && getDtOraIns()
          .equals(other.getDtOraIns());
    }
    result = result && (hasDtOraMod() == other.hasDtOraMod());
    if (hasDtOraMod()) {
      result = result && getDtOraMod()
          .equals(other.getDtOraMod());
    }
    result = result && (hasDtRegistrazione() == other.hasDtRegistrazione());
    if (hasDtRegistrazione()) {
      result = result && getDtRegistrazione()
          .equals(other.getDtRegistrazione());
    }
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && getNome()
        .equals(other.getNome());
    result = result && getProv()
        .equals(other.getProv());
    result = result && getStato()
        .equals(other.getStato());
    result = result && getUseridIns()
        .equals(other.getUseridIns());
    result = result && getUseridMod()
        .equals(other.getUseridMod());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDUTENTE_FIELD_NUMBER;
    hash = (53 * hash) + getIdUtente();
    hash = (37 * hash) + CCOMUNE_FIELD_NUMBER;
    hash = (53 * hash) + getCComune().hashCode();
    hash = (37 * hash) + CFISCALE_FIELD_NUMBER;
    hash = (53 * hash) + getCFiscale().hashCode();
    hash = (37 * hash) + COGNOME_FIELD_NUMBER;
    hash = (53 * hash) + getCognome().hashCode();
    hash = (37 * hash) + DESCRIZIONECOMUNE_FIELD_NUMBER;
    hash = (53 * hash) + getDescrizioneComune().hashCode();
    if (hasDtNascita()) {
      hash = (37 * hash) + DTNASCITA_FIELD_NUMBER;
      hash = (53 * hash) + getDtNascita().hashCode();
    }
    if (hasDtOraIns()) {
      hash = (37 * hash) + DTORAINS_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraIns().hashCode();
    }
    if (hasDtOraMod()) {
      hash = (37 * hash) + DTORAMOD_FIELD_NUMBER;
      hash = (53 * hash) + getDtOraMod().hashCode();
    }
    if (hasDtRegistrazione()) {
      hash = (37 * hash) + DTREGISTRAZIONE_FIELD_NUMBER;
      hash = (53 * hash) + getDtRegistrazione().hashCode();
    }
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + NOME_FIELD_NUMBER;
    hash = (53 * hash) + getNome().hashCode();
    hash = (37 * hash) + PROV_FIELD_NUMBER;
    hash = (53 * hash) + getProv().hashCode();
    hash = (37 * hash) + STATO_FIELD_NUMBER;
    hash = (53 * hash) + getStato().hashCode();
    hash = (37 * hash) + USERIDINS_FIELD_NUMBER;
    hash = (53 * hash) + getUseridIns().hashCode();
    hash = (37 * hash) + USERIDMOD_FIELD_NUMBER;
    hash = (53 * hash) + getUseridMod().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.model.Utente parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gcalsolaro.grpc.artifact.model.Utente prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gcalsolaro.grpc.artifact.model.Utente}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gcalsolaro.grpc.artifact.model.Utente)
      com.gcalsolaro.grpc.artifact.model.UtenteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gcalsolaro.grpc.artifact.model.UtenteOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gcalsolaro.grpc.artifact.model.UtenteOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Utente_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gcalsolaro.grpc.artifact.model.Utente.class, com.gcalsolaro.grpc.artifact.model.Utente.Builder.class);
    }

    // Construct using com.gcalsolaro.grpc.artifact.model.Utente.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      idUtente_ = 0;

      cComune_ = "";

      cFiscale_ = "";

      cognome_ = "";

      descrizioneComune_ = "";

      if (dtNascitaBuilder_ == null) {
        dtNascita_ = null;
      } else {
        dtNascita_ = null;
        dtNascitaBuilder_ = null;
      }
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }
      if (dtRegistrazioneBuilder_ == null) {
        dtRegistrazione_ = null;
      } else {
        dtRegistrazione_ = null;
        dtRegistrazioneBuilder_ = null;
      }
      email_ = "";

      nome_ = "";

      prov_ = "";

      stato_ = "";

      useridIns_ = "";

      useridMod_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gcalsolaro.grpc.artifact.model.UtenteOuterClass.internal_static_com_gcalsolaro_grpc_artifact_model_Utente_descriptor;
    }

    public com.gcalsolaro.grpc.artifact.model.Utente getDefaultInstanceForType() {
      return com.gcalsolaro.grpc.artifact.model.Utente.getDefaultInstance();
    }

    public com.gcalsolaro.grpc.artifact.model.Utente build() {
      com.gcalsolaro.grpc.artifact.model.Utente result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gcalsolaro.grpc.artifact.model.Utente buildPartial() {
      com.gcalsolaro.grpc.artifact.model.Utente result = new com.gcalsolaro.grpc.artifact.model.Utente(this);
      result.idUtente_ = idUtente_;
      result.cComune_ = cComune_;
      result.cFiscale_ = cFiscale_;
      result.cognome_ = cognome_;
      result.descrizioneComune_ = descrizioneComune_;
      if (dtNascitaBuilder_ == null) {
        result.dtNascita_ = dtNascita_;
      } else {
        result.dtNascita_ = dtNascitaBuilder_.build();
      }
      if (dtOraInsBuilder_ == null) {
        result.dtOraIns_ = dtOraIns_;
      } else {
        result.dtOraIns_ = dtOraInsBuilder_.build();
      }
      if (dtOraModBuilder_ == null) {
        result.dtOraMod_ = dtOraMod_;
      } else {
        result.dtOraMod_ = dtOraModBuilder_.build();
      }
      if (dtRegistrazioneBuilder_ == null) {
        result.dtRegistrazione_ = dtRegistrazione_;
      } else {
        result.dtRegistrazione_ = dtRegistrazioneBuilder_.build();
      }
      result.email_ = email_;
      result.nome_ = nome_;
      result.prov_ = prov_;
      result.stato_ = stato_;
      result.useridIns_ = useridIns_;
      result.useridMod_ = useridMod_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gcalsolaro.grpc.artifact.model.Utente) {
        return mergeFrom((com.gcalsolaro.grpc.artifact.model.Utente)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gcalsolaro.grpc.artifact.model.Utente other) {
      if (other == com.gcalsolaro.grpc.artifact.model.Utente.getDefaultInstance()) return this;
      if (other.getIdUtente() != 0) {
        setIdUtente(other.getIdUtente());
      }
      if (!other.getCComune().isEmpty()) {
        cComune_ = other.cComune_;
        onChanged();
      }
      if (!other.getCFiscale().isEmpty()) {
        cFiscale_ = other.cFiscale_;
        onChanged();
      }
      if (!other.getCognome().isEmpty()) {
        cognome_ = other.cognome_;
        onChanged();
      }
      if (!other.getDescrizioneComune().isEmpty()) {
        descrizioneComune_ = other.descrizioneComune_;
        onChanged();
      }
      if (other.hasDtNascita()) {
        mergeDtNascita(other.getDtNascita());
      }
      if (other.hasDtOraIns()) {
        mergeDtOraIns(other.getDtOraIns());
      }
      if (other.hasDtOraMod()) {
        mergeDtOraMod(other.getDtOraMod());
      }
      if (other.hasDtRegistrazione()) {
        mergeDtRegistrazione(other.getDtRegistrazione());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getNome().isEmpty()) {
        nome_ = other.nome_;
        onChanged();
      }
      if (!other.getProv().isEmpty()) {
        prov_ = other.prov_;
        onChanged();
      }
      if (!other.getStato().isEmpty()) {
        stato_ = other.stato_;
        onChanged();
      }
      if (!other.getUseridIns().isEmpty()) {
        useridIns_ = other.useridIns_;
        onChanged();
      }
      if (!other.getUseridMod().isEmpty()) {
        useridMod_ = other.useridMod_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gcalsolaro.grpc.artifact.model.Utente parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gcalsolaro.grpc.artifact.model.Utente) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int idUtente_ ;
    /**
     * <code>int32 idUtente = 1;</code>
     */
    public int getIdUtente() {
      return idUtente_;
    }
    /**
     * <code>int32 idUtente = 1;</code>
     */
    public Builder setIdUtente(int value) {
      
      idUtente_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idUtente = 1;</code>
     */
    public Builder clearIdUtente() {
      
      idUtente_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object cComune_ = "";
    /**
     * <code>string cComune = 2;</code>
     */
    public java.lang.String getCComune() {
      java.lang.Object ref = cComune_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cComune_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cComune = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCComuneBytes() {
      java.lang.Object ref = cComune_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cComune_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cComune = 2;</code>
     */
    public Builder setCComune(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cComune_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cComune = 2;</code>
     */
    public Builder clearCComune() {
      
      cComune_ = getDefaultInstance().getCComune();
      onChanged();
      return this;
    }
    /**
     * <code>string cComune = 2;</code>
     */
    public Builder setCComuneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cComune_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cFiscale_ = "";
    /**
     * <code>string cFiscale = 3;</code>
     */
    public java.lang.String getCFiscale() {
      java.lang.Object ref = cFiscale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cFiscale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCFiscaleBytes() {
      java.lang.Object ref = cFiscale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cFiscale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder setCFiscale(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cFiscale_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder clearCFiscale() {
      
      cFiscale_ = getDefaultInstance().getCFiscale();
      onChanged();
      return this;
    }
    /**
     * <code>string cFiscale = 3;</code>
     */
    public Builder setCFiscaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cFiscale_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cognome_ = "";
    /**
     * <code>string cognome = 4;</code>
     */
    public java.lang.String getCognome() {
      java.lang.Object ref = cognome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cognome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cognome = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCognomeBytes() {
      java.lang.Object ref = cognome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cognome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cognome = 4;</code>
     */
    public Builder setCognome(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cognome_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cognome = 4;</code>
     */
    public Builder clearCognome() {
      
      cognome_ = getDefaultInstance().getCognome();
      onChanged();
      return this;
    }
    /**
     * <code>string cognome = 4;</code>
     */
    public Builder setCognomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cognome_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object descrizioneComune_ = "";
    /**
     * <code>string descrizioneComune = 5;</code>
     */
    public java.lang.String getDescrizioneComune() {
      java.lang.Object ref = descrizioneComune_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descrizioneComune_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string descrizioneComune = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescrizioneComuneBytes() {
      java.lang.Object ref = descrizioneComune_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descrizioneComune_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string descrizioneComune = 5;</code>
     */
    public Builder setDescrizioneComune(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      descrizioneComune_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string descrizioneComune = 5;</code>
     */
    public Builder clearDescrizioneComune() {
      
      descrizioneComune_ = getDefaultInstance().getDescrizioneComune();
      onChanged();
      return this;
    }
    /**
     * <code>string descrizioneComune = 5;</code>
     */
    public Builder setDescrizioneComuneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      descrizioneComune_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dtNascita_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtNascitaBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public boolean hasDtNascita() {
      return dtNascitaBuilder_ != null || dtNascita_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public com.google.protobuf.Timestamp getDtNascita() {
      if (dtNascitaBuilder_ == null) {
        return dtNascita_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtNascita_;
      } else {
        return dtNascitaBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public Builder setDtNascita(com.google.protobuf.Timestamp value) {
      if (dtNascitaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtNascita_ = value;
        onChanged();
      } else {
        dtNascitaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public Builder setDtNascita(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtNascitaBuilder_ == null) {
        dtNascita_ = builderForValue.build();
        onChanged();
      } else {
        dtNascitaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public Builder mergeDtNascita(com.google.protobuf.Timestamp value) {
      if (dtNascitaBuilder_ == null) {
        if (dtNascita_ != null) {
          dtNascita_ =
            com.google.protobuf.Timestamp.newBuilder(dtNascita_).mergeFrom(value).buildPartial();
        } else {
          dtNascita_ = value;
        }
        onChanged();
      } else {
        dtNascitaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public Builder clearDtNascita() {
      if (dtNascitaBuilder_ == null) {
        dtNascita_ = null;
        onChanged();
      } else {
        dtNascita_ = null;
        dtNascitaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtNascitaBuilder() {
      
      onChanged();
      return getDtNascitaFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtNascitaOrBuilder() {
      if (dtNascitaBuilder_ != null) {
        return dtNascitaBuilder_.getMessageOrBuilder();
      } else {
        return dtNascita_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtNascita_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtNascita = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtNascitaFieldBuilder() {
      if (dtNascitaBuilder_ == null) {
        dtNascitaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtNascita(),
                getParentForChildren(),
                isClean());
        dtNascita_ = null;
      }
      return dtNascitaBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraIns_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraInsBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public boolean hasDtOraIns() {
      return dtOraInsBuilder_ != null || dtOraIns_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public com.google.protobuf.Timestamp getDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        return dtOraIns_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      } else {
        return dtOraInsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public Builder setDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraIns_ = value;
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public Builder setDtOraIns(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = builderForValue.build();
        onChanged();
      } else {
        dtOraInsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public Builder mergeDtOraIns(com.google.protobuf.Timestamp value) {
      if (dtOraInsBuilder_ == null) {
        if (dtOraIns_ != null) {
          dtOraIns_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraIns_).mergeFrom(value).buildPartial();
        } else {
          dtOraIns_ = value;
        }
        onChanged();
      } else {
        dtOraInsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public Builder clearDtOraIns() {
      if (dtOraInsBuilder_ == null) {
        dtOraIns_ = null;
        onChanged();
      } else {
        dtOraIns_ = null;
        dtOraInsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraInsBuilder() {
      
      onChanged();
      return getDtOraInsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraInsOrBuilder() {
      if (dtOraInsBuilder_ != null) {
        return dtOraInsBuilder_.getMessageOrBuilder();
      } else {
        return dtOraIns_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraIns_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraIns = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraInsFieldBuilder() {
      if (dtOraInsBuilder_ == null) {
        dtOraInsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraIns(),
                getParentForChildren(),
                isClean());
        dtOraIns_ = null;
      }
      return dtOraInsBuilder_;
    }

    private com.google.protobuf.Timestamp dtOraMod_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtOraModBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public boolean hasDtOraMod() {
      return dtOraModBuilder_ != null || dtOraMod_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public com.google.protobuf.Timestamp getDtOraMod() {
      if (dtOraModBuilder_ == null) {
        return dtOraMod_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      } else {
        return dtOraModBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public Builder setDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtOraMod_ = value;
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public Builder setDtOraMod(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = builderForValue.build();
        onChanged();
      } else {
        dtOraModBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public Builder mergeDtOraMod(com.google.protobuf.Timestamp value) {
      if (dtOraModBuilder_ == null) {
        if (dtOraMod_ != null) {
          dtOraMod_ =
            com.google.protobuf.Timestamp.newBuilder(dtOraMod_).mergeFrom(value).buildPartial();
        } else {
          dtOraMod_ = value;
        }
        onChanged();
      } else {
        dtOraModBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public Builder clearDtOraMod() {
      if (dtOraModBuilder_ == null) {
        dtOraMod_ = null;
        onChanged();
      } else {
        dtOraMod_ = null;
        dtOraModBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtOraModBuilder() {
      
      onChanged();
      return getDtOraModFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtOraModOrBuilder() {
      if (dtOraModBuilder_ != null) {
        return dtOraModBuilder_.getMessageOrBuilder();
      } else {
        return dtOraMod_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtOraMod_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtOraMod = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtOraModFieldBuilder() {
      if (dtOraModBuilder_ == null) {
        dtOraModBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtOraMod(),
                getParentForChildren(),
                isClean());
        dtOraMod_ = null;
      }
      return dtOraModBuilder_;
    }

    private com.google.protobuf.Timestamp dtRegistrazione_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dtRegistrazioneBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public boolean hasDtRegistrazione() {
      return dtRegistrazioneBuilder_ != null || dtRegistrazione_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public com.google.protobuf.Timestamp getDtRegistrazione() {
      if (dtRegistrazioneBuilder_ == null) {
        return dtRegistrazione_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dtRegistrazione_;
      } else {
        return dtRegistrazioneBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public Builder setDtRegistrazione(com.google.protobuf.Timestamp value) {
      if (dtRegistrazioneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dtRegistrazione_ = value;
        onChanged();
      } else {
        dtRegistrazioneBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public Builder setDtRegistrazione(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dtRegistrazioneBuilder_ == null) {
        dtRegistrazione_ = builderForValue.build();
        onChanged();
      } else {
        dtRegistrazioneBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public Builder mergeDtRegistrazione(com.google.protobuf.Timestamp value) {
      if (dtRegistrazioneBuilder_ == null) {
        if (dtRegistrazione_ != null) {
          dtRegistrazione_ =
            com.google.protobuf.Timestamp.newBuilder(dtRegistrazione_).mergeFrom(value).buildPartial();
        } else {
          dtRegistrazione_ = value;
        }
        onChanged();
      } else {
        dtRegistrazioneBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public Builder clearDtRegistrazione() {
      if (dtRegistrazioneBuilder_ == null) {
        dtRegistrazione_ = null;
        onChanged();
      } else {
        dtRegistrazione_ = null;
        dtRegistrazioneBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDtRegistrazioneBuilder() {
      
      onChanged();
      return getDtRegistrazioneFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDtRegistrazioneOrBuilder() {
      if (dtRegistrazioneBuilder_ != null) {
        return dtRegistrazioneBuilder_.getMessageOrBuilder();
      } else {
        return dtRegistrazione_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dtRegistrazione_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dtRegistrazione = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDtRegistrazioneFieldBuilder() {
      if (dtRegistrazioneBuilder_ == null) {
        dtRegistrazioneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDtRegistrazione(),
                getParentForChildren(),
                isClean());
        dtRegistrazione_ = null;
      }
      return dtRegistrazioneBuilder_;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 10;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 10;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 10;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 10;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nome_ = "";
    /**
     * <code>string nome = 11;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nome = 11;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nome = 11;</code>
     */
    public Builder setNome(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nome_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nome = 11;</code>
     */
    public Builder clearNome() {
      
      nome_ = getDefaultInstance().getNome();
      onChanged();
      return this;
    }
    /**
     * <code>string nome = 11;</code>
     */
    public Builder setNomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nome_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object prov_ = "";
    /**
     * <code>string prov = 12;</code>
     */
    public java.lang.String getProv() {
      java.lang.Object ref = prov_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prov_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prov = 12;</code>
     */
    public com.google.protobuf.ByteString
        getProvBytes() {
      java.lang.Object ref = prov_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prov_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prov = 12;</code>
     */
    public Builder setProv(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prov_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prov = 12;</code>
     */
    public Builder clearProv() {
      
      prov_ = getDefaultInstance().getProv();
      onChanged();
      return this;
    }
    /**
     * <code>string prov = 12;</code>
     */
    public Builder setProvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prov_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stato_ = "";
    /**
     * <code>string stato = 13;</code>
     */
    public java.lang.String getStato() {
      java.lang.Object ref = stato_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stato_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stato = 13;</code>
     */
    public com.google.protobuf.ByteString
        getStatoBytes() {
      java.lang.Object ref = stato_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stato_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stato = 13;</code>
     */
    public Builder setStato(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stato_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stato = 13;</code>
     */
    public Builder clearStato() {
      
      stato_ = getDefaultInstance().getStato();
      onChanged();
      return this;
    }
    /**
     * <code>string stato = 13;</code>
     */
    public Builder setStatoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stato_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridIns_ = "";
    /**
     * <code>string useridIns = 14;</code>
     */
    public java.lang.String getUseridIns() {
      java.lang.Object ref = useridIns_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridIns_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUseridInsBytes() {
      java.lang.Object ref = useridIns_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridIns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder setUseridIns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridIns_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder clearUseridIns() {
      
      useridIns_ = getDefaultInstance().getUseridIns();
      onChanged();
      return this;
    }
    /**
     * <code>string useridIns = 14;</code>
     */
    public Builder setUseridInsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridIns_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object useridMod_ = "";
    /**
     * <code>string useridMod = 15;</code>
     */
    public java.lang.String getUseridMod() {
      java.lang.Object ref = useridMod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useridMod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public com.google.protobuf.ByteString
        getUseridModBytes() {
      java.lang.Object ref = useridMod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useridMod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder setUseridMod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      useridMod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder clearUseridMod() {
      
      useridMod_ = getDefaultInstance().getUseridMod();
      onChanged();
      return this;
    }
    /**
     * <code>string useridMod = 15;</code>
     */
    public Builder setUseridModBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      useridMod_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gcalsolaro.grpc.artifact.model.Utente)
  }

  // @@protoc_insertion_point(class_scope:com.gcalsolaro.grpc.artifact.model.Utente)
  private static final com.gcalsolaro.grpc.artifact.model.Utente DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gcalsolaro.grpc.artifact.model.Utente();
  }

  public static com.gcalsolaro.grpc.artifact.model.Utente getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Utente>
      PARSER = new com.google.protobuf.AbstractParser<Utente>() {
    public Utente parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Utente(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Utente> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Utente> getParserForType() {
    return PARSER;
  }

  public com.gcalsolaro.grpc.artifact.model.Utente getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

