// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstanceService.proto

package com.gcalsolaro.grpc.artifact.service;

public interface InstanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.service.InstanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  boolean hasInstance();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  com.gcalsolaro.grpc.artifact.model.Instance getInstance();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder getInstanceOrBuilder();
}
