// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstanceService.proto

package com.gcalsolaro.grpc.artifact.service;

public final class InstanceServiceOuterClass {
  private InstanceServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gcalsolaro_grpc_artifact_service_InstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025InstanceService.proto\022$com.gcalsolaro." +
      "grpc.artifact.service\032\016Instance.proto\"%\n" +
      "\017InstanceRequest\022\022\n\nidInstance\030\001 \001(\005\"c\n\020" +
      "InstanceResponse\022\017\n\007success\030\001 \001(\010\022>\n\010ins" +
      "tance\030\002 \001(\0132,.com.gcalsolaro.grpc.artifa" +
      "ct.model.Instance2\224\001\n\017InstanceService\022\200\001" +
      "\n\017findInstanceApi\0225.com.gcalsolaro.grpc." +
      "artifact.service.InstanceRequest\0326.com.g" +
      "calsolaro.grpc.artifact.service.Instance" +
      "ResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gcalsolaro.grpc.artifact.model.InstanceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gcalsolaro_grpc_artifact_service_InstanceRequest_descriptor,
        new java.lang.String[] { "IdInstance", });
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor,
        new java.lang.String[] { "Success", "Instance", });
    com.gcalsolaro.grpc.artifact.model.InstanceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
