// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IstanzaService.proto

package com.gcalsolaro.grpc.artifact.service;

public interface IstanzaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.service.IstanzaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool esito = 1;</code>
   */
  boolean getEsito();

  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Istanza istanza = 2;</code>
   */
  boolean hasIstanza();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Istanza istanza = 2;</code>
   */
  com.gcalsolaro.grpc.artifact.model.Istanza getIstanza();
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Istanza istanza = 2;</code>
   */
  com.gcalsolaro.grpc.artifact.model.IstanzaOrBuilder getIstanzaOrBuilder();
}
