// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IstanzaService.proto

package com.gcalsolaro.grpc.artifact.service;

/**
 * Protobuf type {@code com.gcalsolaro.grpc.artifact.service.IstanzaRequest}
 */
public  final class IstanzaRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gcalsolaro.grpc.artifact.service.IstanzaRequest)
    IstanzaRequestOrBuilder {
  // Use IstanzaRequest.newBuilder() to construct.
  private IstanzaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IstanzaRequest() {
    idIstanza_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private IstanzaRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            idIstanza_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gcalsolaro.grpc.artifact.service.IstanzaServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_IstanzaRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gcalsolaro.grpc.artifact.service.IstanzaServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_IstanzaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gcalsolaro.grpc.artifact.service.IstanzaRequest.class, com.gcalsolaro.grpc.artifact.service.IstanzaRequest.Builder.class);
  }

  public static final int IDISTANZA_FIELD_NUMBER = 1;
  private int idIstanza_;
  /**
   * <code>int32 idIstanza = 1;</code>
   */
  public int getIdIstanza() {
    return idIstanza_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idIstanza_ != 0) {
      output.writeInt32(1, idIstanza_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idIstanza_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idIstanza_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gcalsolaro.grpc.artifact.service.IstanzaRequest)) {
      return super.equals(obj);
    }
    com.gcalsolaro.grpc.artifact.service.IstanzaRequest other = (com.gcalsolaro.grpc.artifact.service.IstanzaRequest) obj;

    boolean result = true;
    result = result && (getIdIstanza()
        == other.getIdIstanza());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDISTANZA_FIELD_NUMBER;
    hash = (53 * hash) + getIdIstanza();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gcalsolaro.grpc.artifact.service.IstanzaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gcalsolaro.grpc.artifact.service.IstanzaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gcalsolaro.grpc.artifact.service.IstanzaRequest)
      com.gcalsolaro.grpc.artifact.service.IstanzaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gcalsolaro.grpc.artifact.service.IstanzaServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_IstanzaRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gcalsolaro.grpc.artifact.service.IstanzaServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_IstanzaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gcalsolaro.grpc.artifact.service.IstanzaRequest.class, com.gcalsolaro.grpc.artifact.service.IstanzaRequest.Builder.class);
    }

    // Construct using com.gcalsolaro.grpc.artifact.service.IstanzaRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      idIstanza_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gcalsolaro.grpc.artifact.service.IstanzaServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_IstanzaRequest_descriptor;
    }

    public com.gcalsolaro.grpc.artifact.service.IstanzaRequest getDefaultInstanceForType() {
      return com.gcalsolaro.grpc.artifact.service.IstanzaRequest.getDefaultInstance();
    }

    public com.gcalsolaro.grpc.artifact.service.IstanzaRequest build() {
      com.gcalsolaro.grpc.artifact.service.IstanzaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gcalsolaro.grpc.artifact.service.IstanzaRequest buildPartial() {
      com.gcalsolaro.grpc.artifact.service.IstanzaRequest result = new com.gcalsolaro.grpc.artifact.service.IstanzaRequest(this);
      result.idIstanza_ = idIstanza_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gcalsolaro.grpc.artifact.service.IstanzaRequest) {
        return mergeFrom((com.gcalsolaro.grpc.artifact.service.IstanzaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gcalsolaro.grpc.artifact.service.IstanzaRequest other) {
      if (other == com.gcalsolaro.grpc.artifact.service.IstanzaRequest.getDefaultInstance()) return this;
      if (other.getIdIstanza() != 0) {
        setIdIstanza(other.getIdIstanza());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gcalsolaro.grpc.artifact.service.IstanzaRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gcalsolaro.grpc.artifact.service.IstanzaRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int idIstanza_ ;
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public int getIdIstanza() {
      return idIstanza_;
    }
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public Builder setIdIstanza(int value) {
      
      idIstanza_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idIstanza = 1;</code>
     */
    public Builder clearIdIstanza() {
      
      idIstanza_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gcalsolaro.grpc.artifact.service.IstanzaRequest)
  }

  // @@protoc_insertion_point(class_scope:com.gcalsolaro.grpc.artifact.service.IstanzaRequest)
  private static final com.gcalsolaro.grpc.artifact.service.IstanzaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gcalsolaro.grpc.artifact.service.IstanzaRequest();
  }

  public static com.gcalsolaro.grpc.artifact.service.IstanzaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IstanzaRequest>
      PARSER = new com.google.protobuf.AbstractParser<IstanzaRequest>() {
    public IstanzaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new IstanzaRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IstanzaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IstanzaRequest> getParserForType() {
    return PARSER;
  }

  public com.gcalsolaro.grpc.artifact.service.IstanzaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

