// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstanceService.proto

package com.gcalsolaro.grpc.artifact.service;

public interface InstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.service.InstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idInstance = 1;</code>
   */
  int getIdInstance();
}
