// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstanceService.proto

package com.gcalsolaro.grpc.artifact.service;

/**
 * Protobuf type {@code com.gcalsolaro.grpc.artifact.service.InstanceResponse}
 */
public  final class InstanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gcalsolaro.grpc.artifact.service.InstanceResponse)
    InstanceResponseOrBuilder {
  // Use InstanceResponse.newBuilder() to construct.
  private InstanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InstanceResponse() {
    success_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private InstanceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            com.gcalsolaro.grpc.artifact.model.Instance.Builder subBuilder = null;
            if (instance_ != null) {
              subBuilder = instance_.toBuilder();
            }
            instance_ = input.readMessage(com.gcalsolaro.grpc.artifact.model.Instance.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(instance_);
              instance_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gcalsolaro.grpc.artifact.service.InstanceServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gcalsolaro.grpc.artifact.service.InstanceServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gcalsolaro.grpc.artifact.service.InstanceResponse.class, com.gcalsolaro.grpc.artifact.service.InstanceResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int INSTANCE_FIELD_NUMBER = 2;
  private com.gcalsolaro.grpc.artifact.model.Instance instance_;
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  public boolean hasInstance() {
    return instance_ != null;
  }
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.Instance getInstance() {
    return instance_ == null ? com.gcalsolaro.grpc.artifact.model.Instance.getDefaultInstance() : instance_;
  }
  /**
   * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
   */
  public com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder getInstanceOrBuilder() {
    return getInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (instance_ != null) {
      output.writeMessage(2, getInstance());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (instance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInstance());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gcalsolaro.grpc.artifact.service.InstanceResponse)) {
      return super.equals(obj);
    }
    com.gcalsolaro.grpc.artifact.service.InstanceResponse other = (com.gcalsolaro.grpc.artifact.service.InstanceResponse) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (hasInstance() == other.hasInstance());
    if (hasInstance()) {
      result = result && getInstance()
          .equals(other.getInstance());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasInstance()) {
      hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getInstance().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gcalsolaro.grpc.artifact.service.InstanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gcalsolaro.grpc.artifact.service.InstanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gcalsolaro.grpc.artifact.service.InstanceResponse)
      com.gcalsolaro.grpc.artifact.service.InstanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gcalsolaro.grpc.artifact.service.InstanceServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gcalsolaro.grpc.artifact.service.InstanceServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gcalsolaro.grpc.artifact.service.InstanceResponse.class, com.gcalsolaro.grpc.artifact.service.InstanceResponse.Builder.class);
    }

    // Construct using com.gcalsolaro.grpc.artifact.service.InstanceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = false;

      if (instanceBuilder_ == null) {
        instance_ = null;
      } else {
        instance_ = null;
        instanceBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gcalsolaro.grpc.artifact.service.InstanceServiceOuterClass.internal_static_com_gcalsolaro_grpc_artifact_service_InstanceResponse_descriptor;
    }

    public com.gcalsolaro.grpc.artifact.service.InstanceResponse getDefaultInstanceForType() {
      return com.gcalsolaro.grpc.artifact.service.InstanceResponse.getDefaultInstance();
    }

    public com.gcalsolaro.grpc.artifact.service.InstanceResponse build() {
      com.gcalsolaro.grpc.artifact.service.InstanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.gcalsolaro.grpc.artifact.service.InstanceResponse buildPartial() {
      com.gcalsolaro.grpc.artifact.service.InstanceResponse result = new com.gcalsolaro.grpc.artifact.service.InstanceResponse(this);
      result.success_ = success_;
      if (instanceBuilder_ == null) {
        result.instance_ = instance_;
      } else {
        result.instance_ = instanceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gcalsolaro.grpc.artifact.service.InstanceResponse) {
        return mergeFrom((com.gcalsolaro.grpc.artifact.service.InstanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gcalsolaro.grpc.artifact.service.InstanceResponse other) {
      if (other == com.gcalsolaro.grpc.artifact.service.InstanceResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasInstance()) {
        mergeInstance(other.getInstance());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gcalsolaro.grpc.artifact.service.InstanceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gcalsolaro.grpc.artifact.service.InstanceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private com.gcalsolaro.grpc.artifact.model.Instance instance_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Instance, com.gcalsolaro.grpc.artifact.model.Instance.Builder, com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder> instanceBuilder_;
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public boolean hasInstance() {
      return instanceBuilder_ != null || instance_ != null;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Instance getInstance() {
      if (instanceBuilder_ == null) {
        return instance_ == null ? com.gcalsolaro.grpc.artifact.model.Instance.getDefaultInstance() : instance_;
      } else {
        return instanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public Builder setInstance(com.gcalsolaro.grpc.artifact.model.Instance value) {
      if (instanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        instance_ = value;
        onChanged();
      } else {
        instanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public Builder setInstance(
        com.gcalsolaro.grpc.artifact.model.Instance.Builder builderForValue) {
      if (instanceBuilder_ == null) {
        instance_ = builderForValue.build();
        onChanged();
      } else {
        instanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public Builder mergeInstance(com.gcalsolaro.grpc.artifact.model.Instance value) {
      if (instanceBuilder_ == null) {
        if (instance_ != null) {
          instance_ =
            com.gcalsolaro.grpc.artifact.model.Instance.newBuilder(instance_).mergeFrom(value).buildPartial();
        } else {
          instance_ = value;
        }
        onChanged();
      } else {
        instanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public Builder clearInstance() {
      if (instanceBuilder_ == null) {
        instance_ = null;
        onChanged();
      } else {
        instance_ = null;
        instanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.Instance.Builder getInstanceBuilder() {
      
      onChanged();
      return getInstanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    public com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder getInstanceOrBuilder() {
      if (instanceBuilder_ != null) {
        return instanceBuilder_.getMessageOrBuilder();
      } else {
        return instance_ == null ?
            com.gcalsolaro.grpc.artifact.model.Instance.getDefaultInstance() : instance_;
      }
    }
    /**
     * <code>.com.gcalsolaro.grpc.artifact.model.Instance instance = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gcalsolaro.grpc.artifact.model.Instance, com.gcalsolaro.grpc.artifact.model.Instance.Builder, com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder> 
        getInstanceFieldBuilder() {
      if (instanceBuilder_ == null) {
        instanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gcalsolaro.grpc.artifact.model.Instance, com.gcalsolaro.grpc.artifact.model.Instance.Builder, com.gcalsolaro.grpc.artifact.model.InstanceOrBuilder>(
                getInstance(),
                getParentForChildren(),
                isClean());
        instance_ = null;
      }
      return instanceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.gcalsolaro.grpc.artifact.service.InstanceResponse)
  }

  // @@protoc_insertion_point(class_scope:com.gcalsolaro.grpc.artifact.service.InstanceResponse)
  private static final com.gcalsolaro.grpc.artifact.service.InstanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gcalsolaro.grpc.artifact.service.InstanceResponse();
  }

  public static com.gcalsolaro.grpc.artifact.service.InstanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<InstanceResponse>() {
    public InstanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstanceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InstanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstanceResponse> getParserForType() {
    return PARSER;
  }

  public com.gcalsolaro.grpc.artifact.service.InstanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

