// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IstanzaService.proto

package com.gcalsolaro.grpc.artifact.service;

public interface IstanzaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gcalsolaro.grpc.artifact.service.IstanzaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idIstanza = 1;</code>
   */
  int getIdIstanza();
}
